# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from ... import _utilities
from . import outputs

__all__ = [
    'ListWorkplaceRolesResult',
    'AwaitableListWorkplaceRolesResult',
    'list_workplace_roles',
    'list_workplace_roles_output',
]

@pulumi.output_type
class ListWorkplaceRolesResult:
    def __init__(__self__, items=None):
        if items and not isinstance(items, dict):
            raise TypeError("Expected argument 'items' to be a dict")
        pulumi.set(__self__, "items", items)

    @property
    @pulumi.getter
    def items(self) -> 'outputs.ListWorkplaceRolesProperties':
        return pulumi.get(self, "items")


class AwaitableListWorkplaceRolesResult(ListWorkplaceRolesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ListWorkplaceRolesResult(
            items=self.items)


def list_workplace_roles(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableListWorkplaceRolesResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('doppler-native:workplace/v3:listWorkplaceRoles', __args__, opts=opts, typ=ListWorkplaceRolesResult).value

    return AwaitableListWorkplaceRolesResult(
        items=pulumi.get(__ret__, 'items'))


@_utilities.lift_output_func(list_workplace_roles)
def list_workplace_roles_output(opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[ListWorkplaceRolesResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
