// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export function listWorkplaceRolesPermissions(args?: ListWorkplaceRolesPermissionsArgs, opts?: pulumi.InvokeOptions): Promise<outputs.workplace.v3.ListWorkplaceRolesPermissionsProperties> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("doppler-native:workplace/v3:listWorkplaceRolesPermissions", {
    }, opts);
}

export interface ListWorkplaceRolesPermissionsArgs {
}
export function listWorkplaceRolesPermissionsOutput(opts?: pulumi.InvokeOptions): pulumi.Output<outputs.workplace.v3.ListWorkplaceRolesPermissionsProperties> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("doppler-native:workplace/v3:listWorkplaceRolesPermissions", {
    }, opts);
}

