// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export class ServiceAccountToken extends pulumi.CustomResource {
    /**
     * Get an existing ServiceAccountToken resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ServiceAccountToken {
        return new ServiceAccountToken(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler-native:workplace/v3:ServiceAccountToken';

    /**
     * Returns true if the given object is an instance of ServiceAccountToken.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServiceAccountToken {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServiceAccountToken.__pulumiType;
    }

    public /*out*/ readonly apiKey!: pulumi.Output<string | undefined>;
    public /*out*/ readonly apiToken!: pulumi.Output<outputs.workplace.v3.ApiTokenProperties | undefined>;
    /**
     * The datetime at which the API token should expire. If not provided, the API token will remain vaild indefinitely unless manually revoked
     */
    public readonly expiresAt!: pulumi.Output<string | undefined>;
    /**
     * The display name of the API token
     */
    public readonly name!: pulumi.Output<string | undefined>;
    public /*out*/ readonly success!: pulumi.Output<boolean | undefined>;

    /**
     * Create a ServiceAccountToken resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ServiceAccountTokenArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["expiresAt"] = args ? args.expiresAt : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["serviceAccount"] = args ? args.serviceAccount : undefined;
            resourceInputs["apiKey"] = undefined /*out*/;
            resourceInputs["apiToken"] = undefined /*out*/;
            resourceInputs["success"] = undefined /*out*/;
        } else {
            resourceInputs["apiKey"] = undefined /*out*/;
            resourceInputs["apiToken"] = undefined /*out*/;
            resourceInputs["expiresAt"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["success"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ServiceAccountToken.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ServiceAccountToken resource.
 */
export interface ServiceAccountTokenArgs {
    /**
     * The datetime at which the API token should expire. If not provided, the API token will remain vaild indefinitely unless manually revoked
     */
    expiresAt?: pulumi.Input<string>;
    /**
     * The display name of the API token
     */
    name?: pulumi.Input<string>;
    /**
     * Slug of the service account
     */
    serviceAccount?: pulumi.Input<string>;
}
