// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.DopplerNative.ConfigsV3
{
    [DopplerNativeResourceType("doppler-native:configs/v3:ConfigsClone")]
    public partial class ConfigsClone : global::Pulumi.CustomResource
    {
        [Output("config")]
        public Output<Outputs.ConfigProperties> Config { get; private set; } = null!;

        /// <summary>
        /// Name of the new branch config.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Unique identifier for the project object.
        /// </summary>
        [Output("project")]
        public Output<string> Project { get; private set; } = null!;


        /// <summary>
        /// Create a ConfigsClone resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ConfigsClone(string name, ConfigsCloneArgs args, CustomResourceOptions? options = null)
            : base("doppler-native:configs/v3:ConfigsClone", name, args ?? new ConfigsCloneArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ConfigsClone(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("doppler-native:configs/v3:ConfigsClone", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-doppler-native",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ConfigsClone resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ConfigsClone Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ConfigsClone(name, id, options);
        }
    }

    public sealed class ConfigsCloneArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the branch config being cloned.
        /// </summary>
        [Input("config", required: true)]
        public Input<string> Config { get; set; } = null!;

        /// <summary>
        /// Name of the new branch config.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Unique identifier for the project object.
        /// </summary>
        [Input("project", required: true)]
        public Input<string> Project { get; set; } = null!;

        public ConfigsCloneArgs()
        {
            Config = "CONFIG_NAME";
            Name = "NEW_CONFIG_NAME";
            Project = "PROJECT_NAME";
        }
        public static new ConfigsCloneArgs Empty => new ConfigsCloneArgs();
    }
}
