// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v3

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-doppler-native/sdk/go/doppler-native/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSync(ctx *pulumi.Context, args *LookupSyncArgs, opts ...pulumi.InvokeOption) (*LookupSyncResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSyncResult
	err := ctx.Invoke("doppler-native:configs/v3:getSync", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return rv.Defaults(), nil
}

type LookupSyncArgs struct {
}

type LookupSyncResult struct {
	Sync *GetSyncPropertiesSyncProperties `pulumi:"sync"`
}

// Defaults sets the appropriate defaults for LookupSyncResult
func (val *LookupSyncResult) Defaults() *LookupSyncResult {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.Sync = tmp.Sync.Defaults()

	return &tmp
}
func LookupSyncOutput(ctx *pulumi.Context, args LookupSyncOutputArgs, opts ...pulumi.InvokeOption) LookupSyncResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupSyncResultOutput, error) {
			args := v.(LookupSyncArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("doppler-native:configs/v3:getSync", args, LookupSyncResultOutput{}, options).(LookupSyncResultOutput), nil
		}).(LookupSyncResultOutput)
}

type LookupSyncOutputArgs struct {
}

func (LookupSyncOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSyncArgs)(nil)).Elem()
}

type LookupSyncResultOutput struct{ *pulumi.OutputState }

func (LookupSyncResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSyncResult)(nil)).Elem()
}

func (o LookupSyncResultOutput) ToLookupSyncResultOutput() LookupSyncResultOutput {
	return o
}

func (o LookupSyncResultOutput) ToLookupSyncResultOutputWithContext(ctx context.Context) LookupSyncResultOutput {
	return o
}

func (o LookupSyncResultOutput) Sync() GetSyncPropertiesSyncPropertiesPtrOutput {
	return o.ApplyT(func(v LookupSyncResult) *GetSyncPropertiesSyncProperties { return v.Sync }).(GetSyncPropertiesSyncPropertiesPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSyncResultOutput{})
}
