// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v3

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-doppler-native/sdk/go/doppler-native/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func ListServiceTokens(ctx *pulumi.Context, args *ListServiceTokensArgs, opts ...pulumi.InvokeOption) (*ListServiceTokensResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ListServiceTokensResult
	err := ctx.Invoke("doppler-native:configs/v3:listServiceTokens", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ListServiceTokensArgs struct {
}

type ListServiceTokensResult struct {
	Items ListServiceTokensProperties `pulumi:"items"`
}

func ListServiceTokensOutput(ctx *pulumi.Context, args ListServiceTokensOutputArgs, opts ...pulumi.InvokeOption) ListServiceTokensResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ListServiceTokensResult, error) {
			args := v.(ListServiceTokensArgs)
			r, err := ListServiceTokens(ctx, &args, opts...)
			var s ListServiceTokensResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(ListServiceTokensResultOutput)
}

type ListServiceTokensOutputArgs struct {
}

func (ListServiceTokensOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ListServiceTokensArgs)(nil)).Elem()
}

type ListServiceTokensResultOutput struct{ *pulumi.OutputState }

func (ListServiceTokensResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListServiceTokensResult)(nil)).Elem()
}

func (o ListServiceTokensResultOutput) ToListServiceTokensResultOutput() ListServiceTokensResultOutput {
	return o
}

func (o ListServiceTokensResultOutput) ToListServiceTokensResultOutputWithContext(ctx context.Context) ListServiceTokensResultOutput {
	return o
}

func (o ListServiceTokensResultOutput) Items() ListServiceTokensPropertiesOutput {
	return o.ApplyT(func(v ListServiceTokensResult) ListServiceTokensProperties { return v.Items }).(ListServiceTokensPropertiesOutput)
}

func init() {
	pulumi.RegisterOutputType(ListServiceTokensResultOutput{})
}
