// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v3

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType string

const (
	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeString       = SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType("string")
	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeJson         = SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType("json")
	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeJson5        = SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType("json5")
	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeBoolean      = SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType("boolean")
	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeInteger      = SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType("integer")
	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeDecimal      = SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType("decimal")
	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeEmail        = SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType("email")
	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeUrl          = SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType("url")
	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeUuidv4       = SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType("uuidv4")
	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeCuid2        = SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType("cuid2")
	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeUlid         = SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType("ulid")
	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeDatetime8601 = SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType("datetime8601")
	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeDate8601     = SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType("date8601")
	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeYaml         = SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType("yaml")
)

func (SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType) ElementType() reflect.Type {
	return reflect.TypeOf((*SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType)(nil)).Elem()
}

func (e SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType) ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput() SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput {
	return pulumi.ToOutput(e).(SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput)
}

func (e SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType) ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutputWithContext(ctx context.Context) SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput {
	return pulumi.ToOutputWithContext(ctx, e).(SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput)
}

func (e SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType) ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput() SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput {
	return e.ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutputWithContext(context.Background())
}

func (e SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType) ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutputWithContext(ctx context.Context) SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput {
	return SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType(e).ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutputWithContext(ctx).ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutputWithContext(ctx)
}

func (e SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput struct{ *pulumi.OutputState }

func (SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType)(nil)).Elem()
}

func (o SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput) ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput() SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput {
	return o
}

func (o SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput) ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutputWithContext(ctx context.Context) SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput {
	return o
}

func (o SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput) ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput() SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput {
	return o.ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutputWithContext(context.Background())
}

func (o SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput) ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutputWithContext(ctx context.Context) SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType) *SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType {
		return &v
	}).(SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput)
}

func (o SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput struct{ *pulumi.OutputState }

func (SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType)(nil)).Elem()
}

func (o SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput) ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput() SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput {
	return o
}

func (o SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput) ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutputWithContext(ctx context.Context) SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput {
	return o
}

func (o SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput) Elem() SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput {
	return o.ApplyT(func(v *SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType) SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType {
		if v != nil {
			return *v
		}
		var ret SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType
		return ret
	}).(SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput)
}

func (o SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeInput is an input type that accepts values of the SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType enum
// A concrete instance of `SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeInput` can be one of the following:
//
//	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeString
//	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeJson
//	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeJson5
//	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeBoolean
//	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeInteger
//	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeDecimal
//	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeEmail
//	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeUrl
//	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeUuidv4
//	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeCuid2
//	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeUlid
//	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeDatetime8601
//	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeDate8601
//	SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeYaml
type SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeInput interface {
	pulumi.Input

	ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput() SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput
	ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutputWithContext(context.Context) SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput
}

var secretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrType = reflect.TypeOf((**SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType)(nil)).Elem()

type SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrInput interface {
	pulumi.Input

	ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput() SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput
	ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutputWithContext(context.Context) SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput
}

type secretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtr string

func SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtr(v string) SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrInput {
	return (*secretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtr)(&v)
}

func (*secretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtr) ElementType() reflect.Type {
	return secretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrType
}

func (in *secretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtr) ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput() SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput {
	return pulumi.ToOutput(in).(SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput)
}

func (in *secretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtr) ToSecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutputWithContext(ctx context.Context) SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput)
}

type SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType string

const (
	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeString       = SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType("string")
	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeJson         = SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType("json")
	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeJson5        = SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType("json5")
	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeBoolean      = SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType("boolean")
	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeInteger      = SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType("integer")
	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeDecimal      = SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType("decimal")
	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeEmail        = SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType("email")
	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeUrl          = SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType("url")
	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeUuidv4       = SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType("uuidv4")
	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeCuid2        = SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType("cuid2")
	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeUlid         = SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType("ulid")
	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeDatetime8601 = SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType("datetime8601")
	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeDate8601     = SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType("date8601")
	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeYaml         = SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType("yaml")
)

func (SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType) ElementType() reflect.Type {
	return reflect.TypeOf((*SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType)(nil)).Elem()
}

func (e SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType) ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput() SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput {
	return pulumi.ToOutput(e).(SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput)
}

func (e SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType) ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutputWithContext(ctx context.Context) SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput {
	return pulumi.ToOutputWithContext(ctx, e).(SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput)
}

func (e SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType) ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput() SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput {
	return e.ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutputWithContext(context.Background())
}

func (e SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType) ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutputWithContext(ctx context.Context) SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput {
	return SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType(e).ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutputWithContext(ctx).ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutputWithContext(ctx)
}

func (e SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput struct{ *pulumi.OutputState }

func (SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType)(nil)).Elem()
}

func (o SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput) ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput() SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput {
	return o
}

func (o SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput) ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutputWithContext(ctx context.Context) SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput {
	return o
}

func (o SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput) ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput() SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput {
	return o.ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutputWithContext(context.Background())
}

func (o SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput) ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutputWithContext(ctx context.Context) SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType) *SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType {
		return &v
	}).(SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput)
}

func (o SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput struct{ *pulumi.OutputState }

func (SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType)(nil)).Elem()
}

func (o SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput) ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput() SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput {
	return o
}

func (o SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput) ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutputWithContext(ctx context.Context) SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput {
	return o
}

func (o SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput) Elem() SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput {
	return o.ApplyT(func(v *SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType) SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType {
		if v != nil {
			return *v
		}
		var ret SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType
		return ret
	}).(SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput)
}

func (o SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeInput is an input type that accepts values of the SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType enum
// A concrete instance of `SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeInput` can be one of the following:
//
//	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeString
//	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeJson
//	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeJson5
//	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeBoolean
//	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeInteger
//	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeDecimal
//	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeEmail
//	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeUrl
//	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeUuidv4
//	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeCuid2
//	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeUlid
//	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeDatetime8601
//	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeDate8601
//	SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeYaml
type SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeInput interface {
	pulumi.Input

	ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput() SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput
	ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutputWithContext(context.Context) SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput
}

var secretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrType = reflect.TypeOf((**SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType)(nil)).Elem()

type SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrInput interface {
	pulumi.Input

	ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput() SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput
	ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutputWithContext(context.Context) SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput
}

type secretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtr string

func SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtr(v string) SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrInput {
	return (*secretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtr)(&v)
}

func (*secretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtr) ElementType() reflect.Type {
	return secretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrType
}

func (in *secretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtr) ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput() SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput {
	return pulumi.ToOutput(in).(SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput)
}

func (in *secretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtr) ToSecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutputWithContext(ctx context.Context) SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput)
}

// Token's capabilities.
type ServiceTokensAccess string

const (
	ServiceTokensAccessRead      = ServiceTokensAccess("read")
	ServiceTokensAccessReadwrite = ServiceTokensAccess("read/write")
)

func (ServiceTokensAccess) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceTokensAccess)(nil)).Elem()
}

func (e ServiceTokensAccess) ToServiceTokensAccessOutput() ServiceTokensAccessOutput {
	return pulumi.ToOutput(e).(ServiceTokensAccessOutput)
}

func (e ServiceTokensAccess) ToServiceTokensAccessOutputWithContext(ctx context.Context) ServiceTokensAccessOutput {
	return pulumi.ToOutputWithContext(ctx, e).(ServiceTokensAccessOutput)
}

func (e ServiceTokensAccess) ToServiceTokensAccessPtrOutput() ServiceTokensAccessPtrOutput {
	return e.ToServiceTokensAccessPtrOutputWithContext(context.Background())
}

func (e ServiceTokensAccess) ToServiceTokensAccessPtrOutputWithContext(ctx context.Context) ServiceTokensAccessPtrOutput {
	return ServiceTokensAccess(e).ToServiceTokensAccessOutputWithContext(ctx).ToServiceTokensAccessPtrOutputWithContext(ctx)
}

func (e ServiceTokensAccess) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e ServiceTokensAccess) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e ServiceTokensAccess) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e ServiceTokensAccess) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type ServiceTokensAccessOutput struct{ *pulumi.OutputState }

func (ServiceTokensAccessOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceTokensAccess)(nil)).Elem()
}

func (o ServiceTokensAccessOutput) ToServiceTokensAccessOutput() ServiceTokensAccessOutput {
	return o
}

func (o ServiceTokensAccessOutput) ToServiceTokensAccessOutputWithContext(ctx context.Context) ServiceTokensAccessOutput {
	return o
}

func (o ServiceTokensAccessOutput) ToServiceTokensAccessPtrOutput() ServiceTokensAccessPtrOutput {
	return o.ToServiceTokensAccessPtrOutputWithContext(context.Background())
}

func (o ServiceTokensAccessOutput) ToServiceTokensAccessPtrOutputWithContext(ctx context.Context) ServiceTokensAccessPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ServiceTokensAccess) *ServiceTokensAccess {
		return &v
	}).(ServiceTokensAccessPtrOutput)
}

func (o ServiceTokensAccessOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o ServiceTokensAccessOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ServiceTokensAccess) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o ServiceTokensAccessOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ServiceTokensAccessOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ServiceTokensAccess) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type ServiceTokensAccessPtrOutput struct{ *pulumi.OutputState }

func (ServiceTokensAccessPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceTokensAccess)(nil)).Elem()
}

func (o ServiceTokensAccessPtrOutput) ToServiceTokensAccessPtrOutput() ServiceTokensAccessPtrOutput {
	return o
}

func (o ServiceTokensAccessPtrOutput) ToServiceTokensAccessPtrOutputWithContext(ctx context.Context) ServiceTokensAccessPtrOutput {
	return o
}

func (o ServiceTokensAccessPtrOutput) Elem() ServiceTokensAccessOutput {
	return o.ApplyT(func(v *ServiceTokensAccess) ServiceTokensAccess {
		if v != nil {
			return *v
		}
		var ret ServiceTokensAccess
		return ret
	}).(ServiceTokensAccessOutput)
}

func (o ServiceTokensAccessPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ServiceTokensAccessPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *ServiceTokensAccess) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// ServiceTokensAccessInput is an input type that accepts values of the ServiceTokensAccess enum
// A concrete instance of `ServiceTokensAccessInput` can be one of the following:
//
//	ServiceTokensAccessRead
//	ServiceTokensAccessReadwrite
type ServiceTokensAccessInput interface {
	pulumi.Input

	ToServiceTokensAccessOutput() ServiceTokensAccessOutput
	ToServiceTokensAccessOutputWithContext(context.Context) ServiceTokensAccessOutput
}

var serviceTokensAccessPtrType = reflect.TypeOf((**ServiceTokensAccess)(nil)).Elem()

type ServiceTokensAccessPtrInput interface {
	pulumi.Input

	ToServiceTokensAccessPtrOutput() ServiceTokensAccessPtrOutput
	ToServiceTokensAccessPtrOutputWithContext(context.Context) ServiceTokensAccessPtrOutput
}

type serviceTokensAccessPtr string

func ServiceTokensAccessPtr(v string) ServiceTokensAccessPtrInput {
	return (*serviceTokensAccessPtr)(&v)
}

func (*serviceTokensAccessPtr) ElementType() reflect.Type {
	return serviceTokensAccessPtrType
}

func (in *serviceTokensAccessPtr) ToServiceTokensAccessPtrOutput() ServiceTokensAccessPtrOutput {
	return pulumi.ToOutput(in).(ServiceTokensAccessPtrOutput)
}

func (in *serviceTokensAccessPtr) ToServiceTokensAccessPtrOutputWithContext(ctx context.Context) ServiceTokensAccessPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(ServiceTokensAccessPtrOutput)
}

// An option indicating if and how Doppler should attempt to import secrets from the sync destination
type SyncsImportOption string

const (
	SyncsImportOptionNone              = SyncsImportOption("none")
	SyncsImportOptionPreferDoppler     = SyncsImportOption("prefer_doppler")
	SyncsImportOptionPreferIntegration = SyncsImportOption("prefer_integration")
)

func (SyncsImportOption) ElementType() reflect.Type {
	return reflect.TypeOf((*SyncsImportOption)(nil)).Elem()
}

func (e SyncsImportOption) ToSyncsImportOptionOutput() SyncsImportOptionOutput {
	return pulumi.ToOutput(e).(SyncsImportOptionOutput)
}

func (e SyncsImportOption) ToSyncsImportOptionOutputWithContext(ctx context.Context) SyncsImportOptionOutput {
	return pulumi.ToOutputWithContext(ctx, e).(SyncsImportOptionOutput)
}

func (e SyncsImportOption) ToSyncsImportOptionPtrOutput() SyncsImportOptionPtrOutput {
	return e.ToSyncsImportOptionPtrOutputWithContext(context.Background())
}

func (e SyncsImportOption) ToSyncsImportOptionPtrOutputWithContext(ctx context.Context) SyncsImportOptionPtrOutput {
	return SyncsImportOption(e).ToSyncsImportOptionOutputWithContext(ctx).ToSyncsImportOptionPtrOutputWithContext(ctx)
}

func (e SyncsImportOption) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e SyncsImportOption) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e SyncsImportOption) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e SyncsImportOption) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type SyncsImportOptionOutput struct{ *pulumi.OutputState }

func (SyncsImportOptionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SyncsImportOption)(nil)).Elem()
}

func (o SyncsImportOptionOutput) ToSyncsImportOptionOutput() SyncsImportOptionOutput {
	return o
}

func (o SyncsImportOptionOutput) ToSyncsImportOptionOutputWithContext(ctx context.Context) SyncsImportOptionOutput {
	return o
}

func (o SyncsImportOptionOutput) ToSyncsImportOptionPtrOutput() SyncsImportOptionPtrOutput {
	return o.ToSyncsImportOptionPtrOutputWithContext(context.Background())
}

func (o SyncsImportOptionOutput) ToSyncsImportOptionPtrOutputWithContext(ctx context.Context) SyncsImportOptionPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v SyncsImportOption) *SyncsImportOption {
		return &v
	}).(SyncsImportOptionPtrOutput)
}

func (o SyncsImportOptionOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o SyncsImportOptionOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e SyncsImportOption) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o SyncsImportOptionOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o SyncsImportOptionOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e SyncsImportOption) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type SyncsImportOptionPtrOutput struct{ *pulumi.OutputState }

func (SyncsImportOptionPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SyncsImportOption)(nil)).Elem()
}

func (o SyncsImportOptionPtrOutput) ToSyncsImportOptionPtrOutput() SyncsImportOptionPtrOutput {
	return o
}

func (o SyncsImportOptionPtrOutput) ToSyncsImportOptionPtrOutputWithContext(ctx context.Context) SyncsImportOptionPtrOutput {
	return o
}

func (o SyncsImportOptionPtrOutput) Elem() SyncsImportOptionOutput {
	return o.ApplyT(func(v *SyncsImportOption) SyncsImportOption {
		if v != nil {
			return *v
		}
		var ret SyncsImportOption
		return ret
	}).(SyncsImportOptionOutput)
}

func (o SyncsImportOptionPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o SyncsImportOptionPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *SyncsImportOption) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// SyncsImportOptionInput is an input type that accepts values of the SyncsImportOption enum
// A concrete instance of `SyncsImportOptionInput` can be one of the following:
//
//	SyncsImportOptionNone
//	SyncsImportOptionPreferDoppler
//	SyncsImportOptionPreferIntegration
type SyncsImportOptionInput interface {
	pulumi.Input

	ToSyncsImportOptionOutput() SyncsImportOptionOutput
	ToSyncsImportOptionOutputWithContext(context.Context) SyncsImportOptionOutput
}

var syncsImportOptionPtrType = reflect.TypeOf((**SyncsImportOption)(nil)).Elem()

type SyncsImportOptionPtrInput interface {
	pulumi.Input

	ToSyncsImportOptionPtrOutput() SyncsImportOptionPtrOutput
	ToSyncsImportOptionPtrOutputWithContext(context.Context) SyncsImportOptionPtrOutput
}

type syncsImportOptionPtr string

func SyncsImportOptionPtr(v string) SyncsImportOptionPtrInput {
	return (*syncsImportOptionPtr)(&v)
}

func (*syncsImportOptionPtr) ElementType() reflect.Type {
	return syncsImportOptionPtrType
}

func (in *syncsImportOptionPtr) ToSyncsImportOptionPtrOutput() SyncsImportOptionPtrOutput {
	return pulumi.ToOutput(in).(SyncsImportOptionPtrOutput)
}

func (in *syncsImportOptionPtr) ToSyncsImportOptionPtrOutputWithContext(ctx context.Context) SyncsImportOptionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(SyncsImportOptionPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeInput)(nil)).Elem(), SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType("string"))
	pulumi.RegisterInputType(reflect.TypeOf((*SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrInput)(nil)).Elem(), SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType("string"))
	pulumi.RegisterInputType(reflect.TypeOf((*SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeInput)(nil)).Elem(), SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType("string"))
	pulumi.RegisterInputType(reflect.TypeOf((*SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrInput)(nil)).Elem(), SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesType("string"))
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceTokensAccessInput)(nil)).Elem(), ServiceTokensAccess("read"))
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceTokensAccessPtrInput)(nil)).Elem(), ServiceTokensAccess("read"))
	pulumi.RegisterInputType(reflect.TypeOf((*SyncsImportOptionInput)(nil)).Elem(), SyncsImportOption("none"))
	pulumi.RegisterInputType(reflect.TypeOf((*SyncsImportOptionPtrInput)(nil)).Elem(), SyncsImportOption("none"))
	pulumi.RegisterOutputType(SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypeOutput{})
	pulumi.RegisterOutputType(SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesTypePtrOutput{})
	pulumi.RegisterOutputType(SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypeOutput{})
	pulumi.RegisterOutputType(SecretsUpdateChangeRequestsItemPropertiesValueTypePropertiesTypePtrOutput{})
	pulumi.RegisterOutputType(ServiceTokensAccessOutput{})
	pulumi.RegisterOutputType(ServiceTokensAccessPtrOutput{})
	pulumi.RegisterOutputType(SyncsImportOptionOutput{})
	pulumi.RegisterOutputType(SyncsImportOptionPtrOutput{})
}
