// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DopplerNative.ConfigsV3.Outputs
{

    /// <summary>
    /// The valueType you expect the secret to have before `valueType` is applied. If specified, the request will only be processed if the provided valueType matches what's found in Doppler.
    /// </summary>
    [OutputType]
    public sealed class ChangeRequestsItemPropertiesOriginalValueTypeProperties
    {
        public readonly Pulumi.DopplerNative.ConfigsV3.SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType? Type;

        [OutputConstructor]
        private ChangeRequestsItemPropertiesOriginalValueTypeProperties(Pulumi.DopplerNative.ConfigsV3.SecretsUpdateChangeRequestsItemPropertiesOriginalValueTypePropertiesType? type)
        {
            Type = type;
        }
    }
}
