// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DopplerNative.ConfigsV3.Outputs
{

    [OutputType]
    public sealed class ListSecretsPropertiesSecretsProperties
    {
        public readonly Outputs.ListSecretsPropertiesSecretsPropertiesAlgoliaProperties? Algolia;
        public readonly Outputs.ListSecretsPropertiesSecretsPropertiesDatabaseProperties? Database;
        public readonly Outputs.ListSecretsPropertiesSecretsPropertiesStripeProperties? Stripe;
        public readonly Outputs.ListSecretsPropertiesSecretsPropertiesUserProperties? User;

        [OutputConstructor]
        private ListSecretsPropertiesSecretsProperties(
            Outputs.ListSecretsPropertiesSecretsPropertiesAlgoliaProperties? algolia,

            Outputs.ListSecretsPropertiesSecretsPropertiesDatabaseProperties? database,

            Outputs.ListSecretsPropertiesSecretsPropertiesStripeProperties? stripe,

            Outputs.ListSecretsPropertiesSecretsPropertiesUserProperties? user)
        {
            Algolia = algolia;
            Database = database;
            Stripe = stripe;
            User = user;
        }
    }
}
