// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DopplerNative.ConfigsV3.Outputs
{

    [OutputType]
    public sealed class SecretsProperties
    {
        public readonly Outputs.SecretsPropertiesAlgoliaProperties? Algolia;
        public readonly Outputs.SecretsPropertiesDatabaseProperties? Database;
        public readonly Outputs.SecretsPropertiesStripeProperties? Stripe;

        [OutputConstructor]
        private SecretsProperties(
            Outputs.SecretsPropertiesAlgoliaProperties? algolia,

            Outputs.SecretsPropertiesDatabaseProperties? database,

            Outputs.SecretsPropertiesStripeProperties? stripe)
        {
            Algolia = algolia;
            Database = database;
            Stripe = stripe;
        }
    }
}
