# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum

__all__ = [
    'Access',
    'ChangeRequestsItemPropertiesOriginalValueTypePropertiesType',
    'ChangeRequestsItemPropertiesValueTypePropertiesType',
    'ImportOption',
]


class Access(str, Enum):
    """
    Token's capabilities.
    """
    READ = "read"
    READWRITE = "read/write"


class ChangeRequestsItemPropertiesOriginalValueTypePropertiesType(str, Enum):
    STRING = "string"
    JSON = "json"
    JSON5 = "json5"
    BOOLEAN = "boolean"
    INTEGER = "integer"
    DECIMAL = "decimal"
    EMAIL = "email"
    URL = "url"
    UUIDV4 = "uuidv4"
    CUID2 = "cuid2"
    ULID = "ulid"
    DATETIME8601 = "datetime8601"
    DATE8601 = "date8601"
    YAML = "yaml"


class ChangeRequestsItemPropertiesValueTypePropertiesType(str, Enum):
    STRING = "string"
    JSON = "json"
    JSON5 = "json5"
    BOOLEAN = "boolean"
    INTEGER = "integer"
    DECIMAL = "decimal"
    EMAIL = "email"
    URL = "url"
    UUIDV4 = "uuidv4"
    CUID2 = "cuid2"
    ULID = "ulid"
    DATETIME8601 = "datetime8601"
    DATE8601 = "date8601"
    YAML = "yaml"


class ImportOption(str, Enum):
    """
    An option indicating if and how Doppler should attempt to import secrets from the sync destination
    """
    NONE = "none"
    PREFER_DOPPLER = "prefer_doppler"
    PREFER_INTEGRATION = "prefer_integration"
