# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from ... import _utilities
from . import outputs

__all__ = ['ConfigsArgs', 'Configs']

@pulumi.input_type
class ConfigsArgs:
    def __init__(__self__, *,
                 environment: Optional[pulumi.Input[str]] = None,
                 project: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a Configs resource.
        :param pulumi.Input[str] environment: Identifier for the environment object.
        :param pulumi.Input[str] project: Unique identifier for the project object.
        :param pulumi.Input[str] name: Name of the new branch config.
        """
        if environment is None:
            environment = 'ENVIRONMENT_ID'
        pulumi.set(__self__, "environment", environment)
        if project is None:
            project = 'PROJECT_NAME'
        pulumi.set(__self__, "project", project)
        if name is None:
            name = 'CONFIG_NAME'
        if name is not None:
            pulumi.set(__self__, "name", name)

    @property
    @pulumi.getter
    def environment(self) -> pulumi.Input[str]:
        """
        Identifier for the environment object.
        """
        return pulumi.get(self, "environment")

    @environment.setter
    def environment(self, value: pulumi.Input[str]):
        pulumi.set(self, "environment", value)

    @property
    @pulumi.getter
    def project(self) -> pulumi.Input[str]:
        """
        Unique identifier for the project object.
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: pulumi.Input[str]):
        pulumi.set(self, "project", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        Name of the new branch config.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)


class Configs(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 environment: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 project: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a Configs resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] environment: Identifier for the environment object.
        :param pulumi.Input[str] name: Name of the new branch config.
        :param pulumi.Input[str] project: Unique identifier for the project object.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ConfigsArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Configs resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param ConfigsArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ConfigsArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 environment: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 project: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ConfigsArgs.__new__(ConfigsArgs)

            if environment is None:
                environment = 'ENVIRONMENT_ID'
            if environment is None and not opts.urn:
                raise TypeError("Missing required property 'environment'")
            __props__.__dict__["environment"] = environment
            if name is None:
                name = 'CONFIG_NAME'
            __props__.__dict__["name"] = name
            if project is None:
                project = 'PROJECT_NAME'
            if project is None and not opts.urn:
                raise TypeError("Missing required property 'project'")
            __props__.__dict__["project"] = project
            __props__.__dict__["config"] = None
        super(Configs, __self__).__init__(
            'doppler-native:configs/v3:Configs',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Configs':
        """
        Get an existing Configs resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ConfigsArgs.__new__(ConfigsArgs)

        __props__.__dict__["config"] = None
        __props__.__dict__["environment"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["project"] = None
        return Configs(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def config(self) -> pulumi.Output[Optional['outputs.ConfigProperties']]:
        return pulumi.get(self, "config")

    @property
    @pulumi.getter
    def environment(self) -> pulumi.Output[str]:
        """
        Identifier for the environment object.
        """
        return pulumi.get(self, "environment")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        Name of the new branch config.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def project(self) -> pulumi.Output[str]:
        """
        Unique identifier for the project object.
        """
        return pulumi.get(self, "project")

