// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v3

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type WebhooksAuthenticationPropertiesType string

const (
	WebhooksAuthenticationPropertiesTypeNone   = WebhooksAuthenticationPropertiesType("None")
	WebhooksAuthenticationPropertiesTypeBearer = WebhooksAuthenticationPropertiesType("Bearer")
	WebhooksAuthenticationPropertiesTypeBasic  = WebhooksAuthenticationPropertiesType("Basic")
)

func (WebhooksAuthenticationPropertiesType) ElementType() reflect.Type {
	return reflect.TypeOf((*WebhooksAuthenticationPropertiesType)(nil)).Elem()
}

func (e WebhooksAuthenticationPropertiesType) ToWebhooksAuthenticationPropertiesTypeOutput() WebhooksAuthenticationPropertiesTypeOutput {
	return pulumi.ToOutput(e).(WebhooksAuthenticationPropertiesTypeOutput)
}

func (e WebhooksAuthenticationPropertiesType) ToWebhooksAuthenticationPropertiesTypeOutputWithContext(ctx context.Context) WebhooksAuthenticationPropertiesTypeOutput {
	return pulumi.ToOutputWithContext(ctx, e).(WebhooksAuthenticationPropertiesTypeOutput)
}

func (e WebhooksAuthenticationPropertiesType) ToWebhooksAuthenticationPropertiesTypePtrOutput() WebhooksAuthenticationPropertiesTypePtrOutput {
	return e.ToWebhooksAuthenticationPropertiesTypePtrOutputWithContext(context.Background())
}

func (e WebhooksAuthenticationPropertiesType) ToWebhooksAuthenticationPropertiesTypePtrOutputWithContext(ctx context.Context) WebhooksAuthenticationPropertiesTypePtrOutput {
	return WebhooksAuthenticationPropertiesType(e).ToWebhooksAuthenticationPropertiesTypeOutputWithContext(ctx).ToWebhooksAuthenticationPropertiesTypePtrOutputWithContext(ctx)
}

func (e WebhooksAuthenticationPropertiesType) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e WebhooksAuthenticationPropertiesType) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e WebhooksAuthenticationPropertiesType) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e WebhooksAuthenticationPropertiesType) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type WebhooksAuthenticationPropertiesTypeOutput struct{ *pulumi.OutputState }

func (WebhooksAuthenticationPropertiesTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*WebhooksAuthenticationPropertiesType)(nil)).Elem()
}

func (o WebhooksAuthenticationPropertiesTypeOutput) ToWebhooksAuthenticationPropertiesTypeOutput() WebhooksAuthenticationPropertiesTypeOutput {
	return o
}

func (o WebhooksAuthenticationPropertiesTypeOutput) ToWebhooksAuthenticationPropertiesTypeOutputWithContext(ctx context.Context) WebhooksAuthenticationPropertiesTypeOutput {
	return o
}

func (o WebhooksAuthenticationPropertiesTypeOutput) ToWebhooksAuthenticationPropertiesTypePtrOutput() WebhooksAuthenticationPropertiesTypePtrOutput {
	return o.ToWebhooksAuthenticationPropertiesTypePtrOutputWithContext(context.Background())
}

func (o WebhooksAuthenticationPropertiesTypeOutput) ToWebhooksAuthenticationPropertiesTypePtrOutputWithContext(ctx context.Context) WebhooksAuthenticationPropertiesTypePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v WebhooksAuthenticationPropertiesType) *WebhooksAuthenticationPropertiesType {
		return &v
	}).(WebhooksAuthenticationPropertiesTypePtrOutput)
}

func (o WebhooksAuthenticationPropertiesTypeOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o WebhooksAuthenticationPropertiesTypeOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e WebhooksAuthenticationPropertiesType) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o WebhooksAuthenticationPropertiesTypeOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o WebhooksAuthenticationPropertiesTypeOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e WebhooksAuthenticationPropertiesType) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type WebhooksAuthenticationPropertiesTypePtrOutput struct{ *pulumi.OutputState }

func (WebhooksAuthenticationPropertiesTypePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WebhooksAuthenticationPropertiesType)(nil)).Elem()
}

func (o WebhooksAuthenticationPropertiesTypePtrOutput) ToWebhooksAuthenticationPropertiesTypePtrOutput() WebhooksAuthenticationPropertiesTypePtrOutput {
	return o
}

func (o WebhooksAuthenticationPropertiesTypePtrOutput) ToWebhooksAuthenticationPropertiesTypePtrOutputWithContext(ctx context.Context) WebhooksAuthenticationPropertiesTypePtrOutput {
	return o
}

func (o WebhooksAuthenticationPropertiesTypePtrOutput) Elem() WebhooksAuthenticationPropertiesTypeOutput {
	return o.ApplyT(func(v *WebhooksAuthenticationPropertiesType) WebhooksAuthenticationPropertiesType {
		if v != nil {
			return *v
		}
		var ret WebhooksAuthenticationPropertiesType
		return ret
	}).(WebhooksAuthenticationPropertiesTypeOutput)
}

func (o WebhooksAuthenticationPropertiesTypePtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o WebhooksAuthenticationPropertiesTypePtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *WebhooksAuthenticationPropertiesType) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// WebhooksAuthenticationPropertiesTypeInput is an input type that accepts values of the WebhooksAuthenticationPropertiesType enum
// A concrete instance of `WebhooksAuthenticationPropertiesTypeInput` can be one of the following:
//
//	WebhooksAuthenticationPropertiesTypeNone
//	WebhooksAuthenticationPropertiesTypeBearer
//	WebhooksAuthenticationPropertiesTypeBasic
type WebhooksAuthenticationPropertiesTypeInput interface {
	pulumi.Input

	ToWebhooksAuthenticationPropertiesTypeOutput() WebhooksAuthenticationPropertiesTypeOutput
	ToWebhooksAuthenticationPropertiesTypeOutputWithContext(context.Context) WebhooksAuthenticationPropertiesTypeOutput
}

var webhooksAuthenticationPropertiesTypePtrType = reflect.TypeOf((**WebhooksAuthenticationPropertiesType)(nil)).Elem()

type WebhooksAuthenticationPropertiesTypePtrInput interface {
	pulumi.Input

	ToWebhooksAuthenticationPropertiesTypePtrOutput() WebhooksAuthenticationPropertiesTypePtrOutput
	ToWebhooksAuthenticationPropertiesTypePtrOutputWithContext(context.Context) WebhooksAuthenticationPropertiesTypePtrOutput
}

type webhooksAuthenticationPropertiesTypePtr string

func WebhooksAuthenticationPropertiesTypePtr(v string) WebhooksAuthenticationPropertiesTypePtrInput {
	return (*webhooksAuthenticationPropertiesTypePtr)(&v)
}

func (*webhooksAuthenticationPropertiesTypePtr) ElementType() reflect.Type {
	return webhooksAuthenticationPropertiesTypePtrType
}

func (in *webhooksAuthenticationPropertiesTypePtr) ToWebhooksAuthenticationPropertiesTypePtrOutput() WebhooksAuthenticationPropertiesTypePtrOutput {
	return pulumi.ToOutput(in).(WebhooksAuthenticationPropertiesTypePtrOutput)
}

func (in *webhooksAuthenticationPropertiesTypePtr) ToWebhooksAuthenticationPropertiesTypePtrOutputWithContext(ctx context.Context) WebhooksAuthenticationPropertiesTypePtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(WebhooksAuthenticationPropertiesTypePtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WebhooksAuthenticationPropertiesTypeInput)(nil)).Elem(), WebhooksAuthenticationPropertiesType("None"))
	pulumi.RegisterInputType(reflect.TypeOf((*WebhooksAuthenticationPropertiesTypePtrInput)(nil)).Elem(), WebhooksAuthenticationPropertiesType("None"))
	pulumi.RegisterOutputType(WebhooksAuthenticationPropertiesTypeOutput{})
	pulumi.RegisterOutputType(WebhooksAuthenticationPropertiesTypePtrOutput{})
}
