// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export function getProject(args?: GetProjectArgs, opts?: pulumi.InvokeOptions): Promise<GetProjectResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("doppler-native:projects/v3:getProject", {
    }, opts);
}

export interface GetProjectArgs {
}

export interface GetProjectResult {
    readonly items: outputs.projects.v3.GetProjectProperties;
}
export function getProjectOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetProjectResult> {
    return pulumi.output(getProject(opts))
}
