// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Pulumi.DopplerNative.WebhooksV3
{
    [EnumType]
    public readonly struct AuthenticationPropertiesType : IEquatable<AuthenticationPropertiesType>
    {
        private readonly string _value;

        private AuthenticationPropertiesType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static AuthenticationPropertiesType None { get; } = new AuthenticationPropertiesType("None");
        public static AuthenticationPropertiesType Bearer { get; } = new AuthenticationPropertiesType("Bearer");
        public static AuthenticationPropertiesType Basic { get; } = new AuthenticationPropertiesType("Basic");

        public static bool operator ==(AuthenticationPropertiesType left, AuthenticationPropertiesType right) => left.Equals(right);
        public static bool operator !=(AuthenticationPropertiesType left, AuthenticationPropertiesType right) => !left.Equals(right);

        public static explicit operator string(AuthenticationPropertiesType value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is AuthenticationPropertiesType other && Equals(other);
        public bool Equals(AuthenticationPropertiesType other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
