// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v3

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-doppler-native/sdk/go/doppler-native/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetProjectMember(ctx *pulumi.Context, args *GetProjectMemberArgs, opts ...pulumi.InvokeOption) (*GetProjectMemberResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetProjectMemberResult
	err := ctx.Invoke("doppler-native:projects/v3:getProjectMember", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return rv.Defaults(), nil
}

type GetProjectMemberArgs struct {
	// Member's slug
	Slug string `pulumi:"slug"`
	Type string `pulumi:"type"`
}

type GetProjectMemberResult struct {
	Items GetProjectMemberProperties `pulumi:"items"`
}

// Defaults sets the appropriate defaults for GetProjectMemberResult
func (val *GetProjectMemberResult) Defaults() *GetProjectMemberResult {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.Items = *tmp.Items.Defaults()

	return &tmp
}

func GetProjectMemberOutput(ctx *pulumi.Context, args GetProjectMemberOutputArgs, opts ...pulumi.InvokeOption) GetProjectMemberResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetProjectMemberResult, error) {
			args := v.(GetProjectMemberArgs)
			r, err := GetProjectMember(ctx, &args, opts...)
			var s GetProjectMemberResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetProjectMemberResultOutput)
}

type GetProjectMemberOutputArgs struct {
	// Member's slug
	Slug pulumi.StringInput `pulumi:"slug"`
	Type pulumi.StringInput `pulumi:"type"`
}

func (GetProjectMemberOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProjectMemberArgs)(nil)).Elem()
}

type GetProjectMemberResultOutput struct{ *pulumi.OutputState }

func (GetProjectMemberResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProjectMemberResult)(nil)).Elem()
}

func (o GetProjectMemberResultOutput) ToGetProjectMemberResultOutput() GetProjectMemberResultOutput {
	return o
}

func (o GetProjectMemberResultOutput) ToGetProjectMemberResultOutputWithContext(ctx context.Context) GetProjectMemberResultOutput {
	return o
}

func (o GetProjectMemberResultOutput) Items() GetProjectMemberPropertiesOutput {
	return o.ApplyT(func(v GetProjectMemberResult) GetProjectMemberProperties { return v.Items }).(GetProjectMemberPropertiesOutput)
}

func init() {
	pulumi.RegisterOutputType(GetProjectMemberResultOutput{})
}
