// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const GroupsMemberType = {
    WorkplaceUser: "workplace_user",
} as const;

export type GroupsMemberType = (typeof GroupsMemberType)[keyof typeof GroupsMemberType];
