// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

export class WebhooksDisable extends pulumi.CustomResource {
    /**
     * Get an existing WebhooksDisable resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): WebhooksDisable {
        return new WebhooksDisable(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler-native:webhooks/v3:WebhooksDisable';

    /**
     * Returns true if the given object is an instance of WebhooksDisable.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WebhooksDisable {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WebhooksDisable.__pulumiType;
    }


    /**
     * Create a WebhooksDisable resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: WebhooksDisableArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["slug"] = args ? args.slug : undefined;
        } else {
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(WebhooksDisable.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a WebhooksDisable resource.
 */
export interface WebhooksDisableArgs {
    /**
     * Webhook's slug
     */
    slug?: pulumi.Input<string>;
}
