// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export function getAuthMe(args?: GetAuthMeArgs, opts?: pulumi.InvokeOptions): Promise<GetAuthMeResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("doppler-native:me/v3:getAuthMe", {
    }, opts);
}

export interface GetAuthMeArgs {
}

export interface GetAuthMeResult {
    readonly items: outputs.me.v3.GetAuthMeProperties;
}
export function getAuthMeOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetAuthMeResult> {
    return pulumi.output(getAuthMe(opts))
}
