// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Pulumi.DopplerNative.WorkplaceV3
{
    [EnumType]
    public readonly struct GroupsMemberType : IEquatable<GroupsMemberType>
    {
        private readonly string _value;

        private GroupsMemberType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static GroupsMemberType WorkplaceUser { get; } = new GroupsMemberType("workplace_user");

        public static bool operator ==(GroupsMemberType left, GroupsMemberType right) => left.Equals(right);
        public static bool operator !=(GroupsMemberType left, GroupsMemberType right) => !left.Equals(right);

        public static explicit operator string(GroupsMemberType value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is GroupsMemberType other && Equals(other);
        public bool Equals(GroupsMemberType other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
