// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DopplerNative.WorkplaceV3
{
    public static class GetRetrieveMember
    {
        public static Task<GetRetrieveMemberResult> InvokeAsync(GetRetrieveMemberArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRetrieveMemberResult>("doppler-native:workplace/v3:getRetrieveMember", args ?? new GetRetrieveMemberArgs(), options.WithDefaults());

        public static Output<GetRetrieveMemberResult> Invoke(GetRetrieveMemberInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRetrieveMemberResult>("doppler-native:workplace/v3:getRetrieveMember", args ?? new GetRetrieveMemberInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRetrieveMemberArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The group's slug
        /// </summary>
        [Input("groupSlug", required: true)]
        public string GroupSlug { get; set; } = null!;

        /// <summary>
        /// The member's slug
        /// </summary>
        [Input("memberSlug", required: true)]
        public string MemberSlug { get; set; } = null!;

        [Input("memberType", required: true)]
        public string MemberType { get; set; } = null!;

        public GetRetrieveMemberArgs()
        {
        }
        public static new GetRetrieveMemberArgs Empty => new GetRetrieveMemberArgs();
    }

    public sealed class GetRetrieveMemberInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The group's slug
        /// </summary>
        [Input("groupSlug", required: true)]
        public Input<string> GroupSlug { get; set; } = null!;

        /// <summary>
        /// The member's slug
        /// </summary>
        [Input("memberSlug", required: true)]
        public Input<string> MemberSlug { get; set; } = null!;

        [Input("memberType", required: true)]
        public Input<string> MemberType { get; set; } = null!;

        public GetRetrieveMemberInvokeArgs()
        {
        }
        public static new GetRetrieveMemberInvokeArgs Empty => new GetRetrieveMemberInvokeArgs();
    }


    [OutputType]
    public sealed class GetRetrieveMemberResult
    {
        public readonly Outputs.GetRetrieveMemberProperties Items;

        [OutputConstructor]
        private GetRetrieveMemberResult(Outputs.GetRetrieveMemberProperties items)
        {
            Items = items;
        }
    }
}
