// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DopplerNative.WorkplaceV3
{
    [DopplerNativeResourceType("doppler-native:workplace/v3:Groups")]
    public partial class Groups : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Identifier of the project role
        /// </summary>
        [Output("defaultProjectRole")]
        public Output<string?> DefaultProjectRole { get; private set; } = null!;

        [Output("group")]
        public Output<Outputs.GroupProperties?> Group { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;


        /// <summary>
        /// Create a Groups resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Groups(string name, GroupsArgs? args = null, CustomResourceOptions? options = null)
            : base("doppler-native:workplace/v3:Groups", name, args ?? new GroupsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Groups(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("doppler-native:workplace/v3:Groups", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-doppler-native",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Groups resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Groups Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Groups(name, id, options);
        }
    }

    public sealed class GroupsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Identifier of the project role
        /// </summary>
        [Input("defaultProjectRole")]
        public Input<string>? DefaultProjectRole { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public GroupsArgs()
        {
        }
        public static new GroupsArgs Empty => new GroupsArgs();
    }
}
