// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DopplerNative.WorkplaceV3
{
    [DopplerNativeResourceType("doppler-native:workplace/v3:ServiceAccounts")]
    public partial class ServiceAccounts : global::Pulumi.CustomResource
    {
        [Output("name")]
        public Output<string?> Name { get; private set; } = null!;

        [Output("serviceAccount")]
        public Output<Outputs.ServiceAccountProperties?> ServiceAccount { get; private set; } = null!;

        /// <summary>
        /// You may provide an identifier OR permissions, but not both
        /// </summary>
        [Output("workplaceRole")]
        public Output<Outputs.WorkplaceRoleProperties?> WorkplaceRole { get; private set; } = null!;


        /// <summary>
        /// Create a ServiceAccounts resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ServiceAccounts(string name, ServiceAccountsArgs? args = null, CustomResourceOptions? options = null)
            : base("doppler-native:workplace/v3:ServiceAccounts", name, args ?? new ServiceAccountsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ServiceAccounts(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("doppler-native:workplace/v3:ServiceAccounts", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-doppler-native",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ServiceAccounts resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ServiceAccounts Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ServiceAccounts(name, id, options);
        }
    }

    public sealed class ServiceAccountsArgs : global::Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// You may provide an identifier OR permissions, but not both
        /// </summary>
        [Input("workplaceRole")]
        public Input<Inputs.WorkplaceRolePropertiesArgs>? WorkplaceRole { get; set; }

        public ServiceAccountsArgs()
        {
        }
        public static new ServiceAccountsArgs Empty => new ServiceAccountsArgs();
    }
}
