// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

import * as utilities from "../utilities";

export namespace configs {
    export namespace v3 {
        export interface ChangeRequestsItemProperties {
            /**
             * The name of the secret.
             */
            name: string;
            /**
             * The original name of the secret. Use `null` (an actual `null`, not the string `null`) or omit this parameter for new secrets. If it differs from `name` then a rename is inferred.
             */
            originalName: string;
            /**
             * The value you expect the secret to have before `name` is applied. If specified, the request will only be processed if the provided value matches what's found in Doppler.
             */
            originalValue?: string;
            /**
             * The valueType you expect the secret to have before `valueType` is applied. If specified, the request will only be processed if the provided valueType matches what's found in Doppler.
             */
            originalValueType?: outputs.configs.v3.ChangeRequestsItemPropertiesOriginalValueTypeProperties;
            /**
             * Must be set to either `masked`, `unmasked`, or `restricted`. The visibility you expect the secret to have before `visibility` is applied. If specified, the request will only be processed if the provided visibility matches what's found in Doppler.
             */
            originalVisibility?: string;
            /**
             * Defaults to `false`. Can only be set to `true` if the config being updated is a branch config and there is a secret with the same name in the root config. In this case, the branch secret will inherit the value and visibility type from the root secret.
             */
            shouldConverge?: boolean;
            /**
             * Defaults to `false`. If set to `true`, will delete the secret matching the `name` field.
             */
            shouldDelete?: boolean;
            /**
             * Defaults to `false`. Can only be set to `true` if the config being updated is a branch config. If set to `true`, the provided secret will be set in both the branch config as well as the root config in that environment.
             */
            shouldPromote?: boolean;
            /**
             * The value the secret should have. Use `null` (an actual `null`, not the string `null`) to leave the existing secret value unchanged.
             */
            value: string;
            /**
             * The default valueType (string) will result in no validations being applied.
             */
            valueType?: outputs.configs.v3.ChangeRequestsItemPropertiesValueTypeProperties;
            /**
             * Must be set to either `masked`, `unmasked`, or `restricted`.
             */
            visibility?: string;
        }

        /**
         * The valueType you expect the secret to have before `valueType` is applied. If specified, the request will only be processed if the provided valueType matches what's found in Doppler.
         */
        export interface ChangeRequestsItemPropertiesOriginalValueTypeProperties {
            type?: enums.configs.v3.ChangeRequestsItemPropertiesOriginalValueTypePropertiesType;
        }

        /**
         * The default valueType (string) will result in no validations being applied.
         */
        export interface ChangeRequestsItemPropertiesValueTypeProperties {
            type?: enums.configs.v3.ChangeRequestsItemPropertiesValueTypePropertiesType;
        }

        export interface ConfigProperties {
            createdAt?: string;
            environment?: string;
            initialFetchAt?: string;
            lastFetchAt?: string;
            locked?: boolean;
            name?: string;
            project?: string;
            root?: boolean;
        }
        /**
         * configPropertiesProvideDefaults sets the appropriate defaults for ConfigProperties
         */
        export function configPropertiesProvideDefaults(val: ConfigProperties): ConfigProperties {
            return {
                ...val,
                locked: (val.locked) ?? true,
                root: (val.root) ?? true,
            };
        }

        export interface GetConfigLogProperties {
            log?: outputs.configs.v3.GetConfigLogPropertiesLogProperties;
        }
        /**
         * getConfigLogPropertiesProvideDefaults sets the appropriate defaults for GetConfigLogProperties
         */
        export function getConfigLogPropertiesProvideDefaults(val: GetConfigLogProperties): GetConfigLogProperties {
            return {
                ...val,
                log: (val.log ? outputs.configs.v3.getConfigLogPropertiesLogPropertiesProvideDefaults(val.log) : undefined),
            };
        }

        export interface GetConfigLogPropertiesLogProperties {
            config?: string;
            createdAt?: string;
            diff?: outputs.configs.v3.GetConfigLogPropertiesLogPropertiesDiffItemProperties[];
            environment?: string;
            html?: string;
            id?: string;
            project?: string;
            rollback?: boolean;
            text?: string;
            user?: outputs.configs.v3.GetConfigLogPropertiesLogPropertiesUserProperties;
        }
        /**
         * getConfigLogPropertiesLogPropertiesProvideDefaults sets the appropriate defaults for GetConfigLogPropertiesLogProperties
         */
        export function getConfigLogPropertiesLogPropertiesProvideDefaults(val: GetConfigLogPropertiesLogProperties): GetConfigLogPropertiesLogProperties {
            return {
                ...val,
                rollback: (val.rollback) ?? true,
            };
        }

        export interface GetConfigLogPropertiesLogPropertiesDiffItemProperties {
            added?: string;
            name?: string;
        }

        export interface GetConfigLogPropertiesLogPropertiesUserProperties {
            email?: string;
            name?: string;
            profileImageUrl?: string;
            username?: string;
        }

        export interface GetConfigProperties {
            config?: outputs.configs.v3.GetConfigPropertiesConfigProperties;
        }
        /**
         * getConfigPropertiesProvideDefaults sets the appropriate defaults for GetConfigProperties
         */
        export function getConfigPropertiesProvideDefaults(val: GetConfigProperties): GetConfigProperties {
            return {
                ...val,
                config: (val.config ? outputs.configs.v3.getConfigPropertiesConfigPropertiesProvideDefaults(val.config) : undefined),
            };
        }

        export interface GetConfigPropertiesConfigProperties {
            createdAt?: string;
            environment?: string;
            initialFetchAt?: string;
            lastFetchAt?: string;
            locked?: boolean;
            name?: string;
            project?: string;
            root?: boolean;
        }
        /**
         * getConfigPropertiesConfigPropertiesProvideDefaults sets the appropriate defaults for GetConfigPropertiesConfigProperties
         */
        export function getConfigPropertiesConfigPropertiesProvideDefaults(val: GetConfigPropertiesConfigProperties): GetConfigPropertiesConfigProperties {
            return {
                ...val,
                locked: (val.locked) ?? true,
                root: (val.root) ?? true,
            };
        }

        export interface GetSecretProperties {
            name?: string;
            value?: outputs.configs.v3.GetSecretPropertiesValueProperties;
        }

        export interface GetSecretPropertiesValueProperties {
            computed?: string;
            note?: string;
            raw?: string;
        }

        export interface GetSecretsDownloadProperties {
            algolia?: string;
            database?: string;
            stripe?: string;
            user?: string;
        }

        export interface GetSecretsNameProperties {
            names?: string[];
        }

        export interface GetSyncProperties {
            sync?: outputs.configs.v3.GetSyncPropertiesSyncProperties;
        }
        /**
         * getSyncPropertiesProvideDefaults sets the appropriate defaults for GetSyncProperties
         */
        export function getSyncPropertiesProvideDefaults(val: GetSyncProperties): GetSyncProperties {
            return {
                ...val,
                sync: (val.sync ? outputs.configs.v3.getSyncPropertiesSyncPropertiesProvideDefaults(val.sync) : undefined),
            };
        }

        export interface GetSyncPropertiesSyncProperties {
            config?: string;
            enabled?: boolean;
            integration?: string;
            lastSyncedAt?: string;
            project?: string;
            slug?: string;
        }
        /**
         * getSyncPropertiesSyncPropertiesProvideDefaults sets the appropriate defaults for GetSyncPropertiesSyncProperties
         */
        export function getSyncPropertiesSyncPropertiesProvideDefaults(val: GetSyncPropertiesSyncProperties): GetSyncPropertiesSyncProperties {
            return {
                ...val,
                enabled: (val.enabled) ?? true,
            };
        }

        export interface ListConfigLogsProperties {
            logs?: outputs.configs.v3.ListConfigLogsPropertiesLogsItemProperties[];
            page?: number;
        }
        /**
         * listConfigLogsPropertiesProvideDefaults sets the appropriate defaults for ListConfigLogsProperties
         */
        export function listConfigLogsPropertiesProvideDefaults(val: ListConfigLogsProperties): ListConfigLogsProperties {
            return {
                ...val,
                page: (val.page) ?? 0,
            };
        }

        export interface ListConfigLogsPropertiesLogsItemProperties {
            config?: string;
            createdAt?: string;
            environment?: string;
            html?: string;
            id?: string;
            project?: string;
            rollback?: boolean;
            text?: string;
            user?: outputs.configs.v3.ListConfigLogsPropertiesLogsItemPropertiesUserProperties;
        }
        /**
         * listConfigLogsPropertiesLogsItemPropertiesProvideDefaults sets the appropriate defaults for ListConfigLogsPropertiesLogsItemProperties
         */
        export function listConfigLogsPropertiesLogsItemPropertiesProvideDefaults(val: ListConfigLogsPropertiesLogsItemProperties): ListConfigLogsPropertiesLogsItemProperties {
            return {
                ...val,
                rollback: (val.rollback) ?? true,
            };
        }

        export interface ListConfigLogsPropertiesLogsItemPropertiesUserProperties {
            email?: string;
            name?: string;
            profileImageUrl?: string;
            username?: string;
        }

        export interface ListConfigsProperties {
            configs?: outputs.configs.v3.ListConfigsPropertiesConfigsItemProperties[];
            page?: number;
        }
        /**
         * listConfigsPropertiesProvideDefaults sets the appropriate defaults for ListConfigsProperties
         */
        export function listConfigsPropertiesProvideDefaults(val: ListConfigsProperties): ListConfigsProperties {
            return {
                ...val,
                page: (val.page) ?? 0,
            };
        }

        export interface ListConfigsPropertiesConfigsItemProperties {
            createdAt?: string;
            environment?: string;
            initialFetchAt?: string;
            lastFetchAt?: string;
            locked?: boolean;
            name?: string;
            project?: string;
            root?: boolean;
        }
        /**
         * listConfigsPropertiesConfigsItemPropertiesProvideDefaults sets the appropriate defaults for ListConfigsPropertiesConfigsItemProperties
         */
        export function listConfigsPropertiesConfigsItemPropertiesProvideDefaults(val: ListConfigsPropertiesConfigsItemProperties): ListConfigsPropertiesConfigsItemProperties {
            return {
                ...val,
                locked: (val.locked) ?? true,
                root: (val.root) ?? true,
            };
        }

        export interface ListConfigsTrustedIpsProperties {
            ips?: string[];
        }

        export interface ListSecretsProperties {
            secrets?: outputs.configs.v3.ListSecretsPropertiesSecretsProperties;
        }

        export interface ListSecretsPropertiesSecretsProperties {
            algolia?: outputs.configs.v3.ListSecretsPropertiesSecretsPropertiesAlgoliaProperties;
            database?: outputs.configs.v3.ListSecretsPropertiesSecretsPropertiesDatabaseProperties;
            stripe?: outputs.configs.v3.ListSecretsPropertiesSecretsPropertiesStripeProperties;
            user?: outputs.configs.v3.ListSecretsPropertiesSecretsPropertiesUserProperties;
        }

        export interface ListSecretsPropertiesSecretsPropertiesAlgoliaProperties {
            computed?: string;
            computedVisibility?: string;
            note?: string;
            raw?: string;
            rawVisibility?: string;
        }

        export interface ListSecretsPropertiesSecretsPropertiesDatabaseProperties {
            computed?: string;
            computedVisibility?: string;
            note?: string;
            raw?: string;
            rawVisibility?: string;
        }

        export interface ListSecretsPropertiesSecretsPropertiesStripeProperties {
            computed?: string;
            computedVisibility?: string;
            note?: string;
            raw?: string;
            rawVisibility?: string;
        }

        export interface ListSecretsPropertiesSecretsPropertiesUserProperties {
            computed?: string;
            computedVisibility?: string;
            note?: string;
            raw?: string;
            rawVisibility?: string;
        }

        export interface ListServiceTokensProperties {
            tokens?: outputs.configs.v3.ListServiceTokensPropertiesTokensItemProperties[];
        }

        export interface ListServiceTokensPropertiesTokensItemProperties {
            config?: string;
            createdAt?: string;
            environment?: string;
            expiresAt?: string;
            name?: string;
            project?: string;
            slug?: string;
        }

        export interface LogProperties {
            config?: string;
            createdAt?: string;
            diff?: outputs.configs.v3.LogPropertiesDiffItemProperties[];
            environment?: string;
            html?: string;
            id?: string;
            project?: string;
            rollback?: boolean;
            text?: string;
            user?: outputs.configs.v3.LogPropertiesUserProperties;
        }
        /**
         * logPropertiesProvideDefaults sets the appropriate defaults for LogProperties
         */
        export function logPropertiesProvideDefaults(val: LogProperties): LogProperties {
            return {
                ...val,
                rollback: (val.rollback) ?? true,
            };
        }

        export interface LogPropertiesDiffItemProperties {
            name?: string;
            removed?: string;
        }

        export interface LogPropertiesUserProperties {
            email?: string;
            name?: string;
            profileImageUrl?: string;
            username?: string;
        }

        export interface SecretsProperties {
            algolia?: outputs.configs.v3.SecretsPropertiesAlgoliaProperties;
            database?: outputs.configs.v3.SecretsPropertiesDatabaseProperties;
            stripe?: outputs.configs.v3.SecretsPropertiesStripeProperties;
        }

        export interface SecretsPropertiesAlgoliaProperties {
            computed?: string;
            note?: string;
            raw?: string;
        }

        export interface SecretsPropertiesDatabaseProperties {
            computed?: string;
            note?: string;
            raw?: string;
        }

        export interface SecretsPropertiesStripeProperties {
            computed?: string;
            note?: string;
            raw?: string;
        }

        export interface SyncProperties {
            config?: string;
            enabled?: boolean;
            integration?: string;
            lastSyncedAt?: string;
            project?: string;
            slug?: string;
        }
        /**
         * syncPropertiesProvideDefaults sets the appropriate defaults for SyncProperties
         */
        export function syncPropertiesProvideDefaults(val: SyncProperties): SyncProperties {
            return {
                ...val,
                enabled: (val.enabled) ?? true,
            };
        }

        export interface TokenProperties {
            access?: string;
            config?: string;
            createdAt?: string;
            environment?: string;
            expiresAt?: string;
            key?: string;
            name?: string;
            project?: string;
            slug?: string;
        }

    }
}

export namespace environments {
    export namespace v3 {
        export interface EnvironmentProperties {
            createdAt?: string;
            id?: string;
            initialFetchAt?: string;
            name?: string;
            project?: string;
        }

        export interface GetEnvironmentProperties {
            environment?: outputs.environments.v3.GetEnvironmentPropertiesEnvironmentProperties;
        }

        export interface GetEnvironmentPropertiesEnvironmentProperties {
            createdAt?: string;
            id?: string;
            initialFetchAt?: string;
            name?: string;
            project?: string;
        }

        export interface ListEnvironmentsProperties {
            environments?: outputs.environments.v3.ListEnvironmentsPropertiesEnvironmentsItemProperties[];
            page?: number;
        }
        /**
         * listEnvironmentsPropertiesProvideDefaults sets the appropriate defaults for ListEnvironmentsProperties
         */
        export function listEnvironmentsPropertiesProvideDefaults(val: ListEnvironmentsProperties): ListEnvironmentsProperties {
            return {
                ...val,
                page: (val.page) ?? 0,
            };
        }

        export interface ListEnvironmentsPropertiesEnvironmentsItemProperties {
            createdAt?: string;
            id?: string;
            initialFetchAt?: string;
            name?: string;
            project?: string;
        }

    }
}

export namespace integrations {
    export namespace v3 {
        export interface GetIntegrationProperties {
            integration?: outputs.integrations.v3.GetIntegrationPropertiesIntegrationProperties;
        }

        export interface GetIntegrationPropertiesIntegrationProperties {
            name?: string;
            slug?: string;
            type?: string;
        }

        export interface IntegrationProperties {
            name?: string;
            slug?: string;
            type?: string;
        }

        export interface ListIntegrationsProperties {
            integrations?: outputs.integrations.v3.ListIntegrationsPropertiesIntegrationsItemProperties[];
            success?: boolean;
        }
        /**
         * listIntegrationsPropertiesProvideDefaults sets the appropriate defaults for ListIntegrationsProperties
         */
        export function listIntegrationsPropertiesProvideDefaults(val: ListIntegrationsProperties): ListIntegrationsProperties {
            return {
                ...val,
                success: (val.success) ?? true,
            };
        }

        export interface ListIntegrationsPropertiesIntegrationsItemProperties {
            enabled?: boolean;
            kind?: string;
            name?: string;
            slug?: string;
            type?: string;
        }
        /**
         * listIntegrationsPropertiesIntegrationsItemPropertiesProvideDefaults sets the appropriate defaults for ListIntegrationsPropertiesIntegrationsItemProperties
         */
        export function listIntegrationsPropertiesIntegrationsItemPropertiesProvideDefaults(val: ListIntegrationsPropertiesIntegrationsItemProperties): ListIntegrationsPropertiesIntegrationsItemProperties {
            return {
                ...val,
                enabled: (val.enabled) ?? true,
            };
        }

    }
}

export namespace me {
    export namespace v3 {
        export interface GetAuthMeProperties {
            createdAt?: string;
            lastSeenAt?: string;
            name?: string;
            slug?: string;
            tokenPreview?: string;
            type?: string;
            workplace?: outputs.me.v3.GetAuthMePropertiesWorkplaceProperties;
        }

        export interface GetAuthMePropertiesWorkplaceProperties {
            name?: string;
            slug?: string;
        }

    }
}

export namespace projects {
    export namespace v3 {
        export interface GetProjectMemberProperties {
            member?: outputs.projects.v3.GetProjectMemberPropertiesMemberProperties;
        }
        /**
         * getProjectMemberPropertiesProvideDefaults sets the appropriate defaults for GetProjectMemberProperties
         */
        export function getProjectMemberPropertiesProvideDefaults(val: GetProjectMemberProperties): GetProjectMemberProperties {
            return {
                ...val,
                member: (val.member ? outputs.projects.v3.getProjectMemberPropertiesMemberPropertiesProvideDefaults(val.member) : undefined),
            };
        }

        export interface GetProjectMemberPropertiesMemberProperties {
            accessAllEnvironments?: boolean;
            environments?: string[];
            role?: outputs.projects.v3.GetProjectMemberPropertiesMemberPropertiesRoleProperties;
            slug?: string;
            type?: string;
        }
        /**
         * getProjectMemberPropertiesMemberPropertiesProvideDefaults sets the appropriate defaults for GetProjectMemberPropertiesMemberProperties
         */
        export function getProjectMemberPropertiesMemberPropertiesProvideDefaults(val: GetProjectMemberPropertiesMemberProperties): GetProjectMemberPropertiesMemberProperties {
            return {
                ...val,
                accessAllEnvironments: (val.accessAllEnvironments) ?? true,
            };
        }

        export interface GetProjectMemberPropertiesMemberPropertiesRoleProperties {
            identifier?: string;
        }

        export interface GetProjectProperties {
            project?: outputs.projects.v3.GetProjectPropertiesProjectProperties;
        }

        export interface GetProjectPropertiesProjectProperties {
            createdAt?: string;
            description?: string;
            id?: string;
            name?: string;
        }

        export interface GetProjectRoleProperties {
            role?: outputs.projects.v3.GetProjectRolePropertiesRoleProperties;
        }
        /**
         * getProjectRolePropertiesProvideDefaults sets the appropriate defaults for GetProjectRoleProperties
         */
        export function getProjectRolePropertiesProvideDefaults(val: GetProjectRoleProperties): GetProjectRoleProperties {
            return {
                ...val,
                role: (val.role ? outputs.projects.v3.getProjectRolePropertiesRolePropertiesProvideDefaults(val.role) : undefined),
            };
        }

        export interface GetProjectRolePropertiesRoleProperties {
            createdAt?: string;
            identifier?: string;
            isCustomRole?: boolean;
            name?: string;
            permissions?: string[];
        }
        /**
         * getProjectRolePropertiesRolePropertiesProvideDefaults sets the appropriate defaults for GetProjectRolePropertiesRoleProperties
         */
        export function getProjectRolePropertiesRolePropertiesProvideDefaults(val: GetProjectRolePropertiesRoleProperties): GetProjectRolePropertiesRoleProperties {
            return {
                ...val,
                isCustomRole: (val.isCustomRole) ?? true,
            };
        }

        export interface ListProjectMembersProperties {
            members?: outputs.projects.v3.ListProjectMembersPropertiesMembersItemProperties[];
        }

        export interface ListProjectMembersPropertiesMembersItemProperties {
            accessAllEnvironments?: boolean;
            environments?: string[];
            role?: outputs.projects.v3.ListProjectMembersPropertiesMembersItemPropertiesRoleProperties;
            slug?: string;
            type?: string;
        }
        /**
         * listProjectMembersPropertiesMembersItemPropertiesProvideDefaults sets the appropriate defaults for ListProjectMembersPropertiesMembersItemProperties
         */
        export function listProjectMembersPropertiesMembersItemPropertiesProvideDefaults(val: ListProjectMembersPropertiesMembersItemProperties): ListProjectMembersPropertiesMembersItemProperties {
            return {
                ...val,
                accessAllEnvironments: (val.accessAllEnvironments) ?? true,
            };
        }

        export interface ListProjectMembersPropertiesMembersItemPropertiesRoleProperties {
            identifier?: string;
        }

        export interface ListProjectRolesPermissionsProperties {
            permissions?: string[];
        }

        export interface ListProjectRolesProperties {
            roles?: outputs.projects.v3.ListProjectRolesPropertiesRolesItemProperties[];
        }

        export interface ListProjectRolesPropertiesRolesItemProperties {
            createdAt?: string;
            identifier?: string;
            isCustomRole?: boolean;
            name?: string;
            permissions?: string[];
        }
        /**
         * listProjectRolesPropertiesRolesItemPropertiesProvideDefaults sets the appropriate defaults for ListProjectRolesPropertiesRolesItemProperties
         */
        export function listProjectRolesPropertiesRolesItemPropertiesProvideDefaults(val: ListProjectRolesPropertiesRolesItemProperties): ListProjectRolesPropertiesRolesItemProperties {
            return {
                ...val,
                isCustomRole: (val.isCustomRole) ?? true,
            };
        }

        export interface ListProjectsProperties {
            page?: number;
            projects?: outputs.projects.v3.ListProjectsPropertiesProjectsItemProperties[];
        }
        /**
         * listProjectsPropertiesProvideDefaults sets the appropriate defaults for ListProjectsProperties
         */
        export function listProjectsPropertiesProvideDefaults(val: ListProjectsProperties): ListProjectsProperties {
            return {
                ...val,
                page: (val.page) ?? 0,
            };
        }

        export interface ListProjectsPropertiesProjectsItemProperties {
            createdAt?: string;
            description?: string;
            id?: string;
            name?: string;
            slug?: string;
        }

        export interface MemberProperties {
            accessAllEnvironments?: boolean;
            environments?: string[];
            role?: outputs.projects.v3.MemberPropertiesRoleProperties;
            slug?: string;
            type?: string;
        }
        /**
         * memberPropertiesProvideDefaults sets the appropriate defaults for MemberProperties
         */
        export function memberPropertiesProvideDefaults(val: MemberProperties): MemberProperties {
            return {
                ...val,
                accessAllEnvironments: (val.accessAllEnvironments) ?? true,
            };
        }

        export interface MemberPropertiesRoleProperties {
            identifier?: string;
        }

        export interface ProjectProperties {
            createdAt?: string;
            description?: string;
            id?: string;
            name?: string;
        }

        export interface RoleProperties {
            createdAt?: string;
            identifier?: string;
            isCustomRole?: boolean;
            name?: string;
            permissions?: string[];
        }
        /**
         * rolePropertiesProvideDefaults sets the appropriate defaults for RoleProperties
         */
        export function rolePropertiesProvideDefaults(val: RoleProperties): RoleProperties {
            return {
                ...val,
                isCustomRole: (val.isCustomRole) ?? true,
            };
        }

    }
}

export namespace workplace {
    export namespace v3 {
        export interface ApiTokenProperties {
            createdAt?: string;
            expiresAt?: string;
            lastSeenAt?: string;
            name?: string;
            slug?: string;
        }

        export interface GetAuditUserProperties {
            success?: boolean;
            workplaceUser?: outputs.workplace.v3.GetAuditUserPropertiesWorkplaceUserProperties;
        }
        /**
         * getAuditUserPropertiesProvideDefaults sets the appropriate defaults for GetAuditUserProperties
         */
        export function getAuditUserPropertiesProvideDefaults(val: GetAuditUserProperties): GetAuditUserProperties {
            return {
                ...val,
                success: (val.success) ?? true,
                workplaceUser: (val.workplaceUser ? outputs.workplace.v3.getAuditUserPropertiesWorkplaceUserPropertiesProvideDefaults(val.workplaceUser) : undefined),
            };
        }

        export interface GetAuditUserPropertiesWorkplaceUserProperties {
            access?: string;
            createdAt?: string;
            id?: string;
            user?: outputs.workplace.v3.GetAuditUserPropertiesWorkplaceUserPropertiesUserProperties;
        }
        /**
         * getAuditUserPropertiesWorkplaceUserPropertiesProvideDefaults sets the appropriate defaults for GetAuditUserPropertiesWorkplaceUserProperties
         */
        export function getAuditUserPropertiesWorkplaceUserPropertiesProvideDefaults(val: GetAuditUserPropertiesWorkplaceUserProperties): GetAuditUserPropertiesWorkplaceUserProperties {
            return {
                ...val,
                user: (val.user ? outputs.workplace.v3.getAuditUserPropertiesWorkplaceUserPropertiesUserPropertiesProvideDefaults(val.user) : undefined),
            };
        }

        export interface GetAuditUserPropertiesWorkplaceUserPropertiesUserProperties {
            email?: string;
            mfaEnabled?: boolean;
            name?: string;
            profileImageUrl?: string;
            samlSsoEnabled?: boolean;
            thirdpartySsoEnabled?: boolean;
            username?: string;
        }
        /**
         * getAuditUserPropertiesWorkplaceUserPropertiesUserPropertiesProvideDefaults sets the appropriate defaults for GetAuditUserPropertiesWorkplaceUserPropertiesUserProperties
         */
        export function getAuditUserPropertiesWorkplaceUserPropertiesUserPropertiesProvideDefaults(val: GetAuditUserPropertiesWorkplaceUserPropertiesUserProperties): GetAuditUserPropertiesWorkplaceUserPropertiesUserProperties {
            return {
                ...val,
                mfaEnabled: (val.mfaEnabled) ?? true,
                samlSsoEnabled: (val.samlSsoEnabled) ?? true,
                thirdpartySsoEnabled: (val.thirdpartySsoEnabled) ?? true,
            };
        }

        export interface GetGroupProperties {
            group?: outputs.workplace.v3.GetGroupPropertiesGroupProperties;
        }

        export interface GetGroupPropertiesGroupProperties {
            createdAt?: string;
            defaultProjectRole?: outputs.workplace.v3.GetGroupPropertiesGroupPropertiesDefaultProjectRoleProperties;
            members?: outputs.workplace.v3.GetGroupPropertiesGroupPropertiesMembersItemProperties[];
            name?: string;
            projects?: outputs.workplace.v3.GetGroupPropertiesGroupPropertiesProjectsItemProperties[];
            slug?: string;
        }

        export interface GetGroupPropertiesGroupPropertiesDefaultProjectRoleProperties {
            identifier?: string;
        }

        export interface GetGroupPropertiesGroupPropertiesMembersItemProperties {
            slug?: string;
            type?: string;
        }

        export interface GetGroupPropertiesGroupPropertiesProjectsItemProperties {
            name?: string;
            role?: outputs.workplace.v3.GetGroupPropertiesGroupPropertiesProjectsItemPropertiesRoleProperties;
            slug?: string;
        }

        export interface GetGroupPropertiesGroupPropertiesProjectsItemPropertiesRoleProperties {
            identifier?: string;
        }

        export interface GetMemberProperties {
            group?: outputs.workplace.v3.GetMemberPropertiesGroupProperties;
        }

        export interface GetMemberPropertiesGroupProperties {
            createdAt?: string;
            defaultProjectRole?: outputs.workplace.v3.GetMemberPropertiesGroupPropertiesDefaultProjectRoleProperties;
            members?: outputs.workplace.v3.GetMemberPropertiesGroupPropertiesMembersItemProperties[];
            name?: string;
            projects?: outputs.workplace.v3.GetMemberPropertiesGroupPropertiesProjectsItemProperties[];
            slug?: string;
        }

        export interface GetMemberPropertiesGroupPropertiesDefaultProjectRoleProperties {
            identifier?: string;
        }

        export interface GetMemberPropertiesGroupPropertiesMembersItemProperties {
            slug?: string;
            type?: string;
        }

        export interface GetMemberPropertiesGroupPropertiesProjectsItemProperties {
            name?: string;
            role?: outputs.workplace.v3.GetMemberPropertiesGroupPropertiesProjectsItemPropertiesRoleProperties;
            slug?: string;
        }

        export interface GetMemberPropertiesGroupPropertiesProjectsItemPropertiesRoleProperties {
            identifier?: string;
        }

        export interface GetServiceAccountProperties {
            serviceAccount?: outputs.workplace.v3.GetServiceAccountPropertiesServiceAccountProperties;
        }
        /**
         * getServiceAccountPropertiesProvideDefaults sets the appropriate defaults for GetServiceAccountProperties
         */
        export function getServiceAccountPropertiesProvideDefaults(val: GetServiceAccountProperties): GetServiceAccountProperties {
            return {
                ...val,
                serviceAccount: (val.serviceAccount ? outputs.workplace.v3.getServiceAccountPropertiesServiceAccountPropertiesProvideDefaults(val.serviceAccount) : undefined),
            };
        }

        export interface GetServiceAccountPropertiesServiceAccountProperties {
            createdAt?: string;
            name?: string;
            slug?: string;
            workplaceRole?: outputs.workplace.v3.GetServiceAccountPropertiesServiceAccountPropertiesWorkplaceRoleProperties;
        }
        /**
         * getServiceAccountPropertiesServiceAccountPropertiesProvideDefaults sets the appropriate defaults for GetServiceAccountPropertiesServiceAccountProperties
         */
        export function getServiceAccountPropertiesServiceAccountPropertiesProvideDefaults(val: GetServiceAccountPropertiesServiceAccountProperties): GetServiceAccountPropertiesServiceAccountProperties {
            return {
                ...val,
                workplaceRole: (val.workplaceRole ? outputs.workplace.v3.getServiceAccountPropertiesServiceAccountPropertiesWorkplaceRolePropertiesProvideDefaults(val.workplaceRole) : undefined),
            };
        }

        export interface GetServiceAccountPropertiesServiceAccountPropertiesWorkplaceRoleProperties {
            createdAt?: string;
            identifier?: string;
            isCustomRole?: boolean;
            isInlineRole?: boolean;
            name?: string;
            permissions?: string[];
        }
        /**
         * getServiceAccountPropertiesServiceAccountPropertiesWorkplaceRolePropertiesProvideDefaults sets the appropriate defaults for GetServiceAccountPropertiesServiceAccountPropertiesWorkplaceRoleProperties
         */
        export function getServiceAccountPropertiesServiceAccountPropertiesWorkplaceRolePropertiesProvideDefaults(val: GetServiceAccountPropertiesServiceAccountPropertiesWorkplaceRoleProperties): GetServiceAccountPropertiesServiceAccountPropertiesWorkplaceRoleProperties {
            return {
                ...val,
                isCustomRole: (val.isCustomRole) ?? true,
                isInlineRole: (val.isInlineRole) ?? true,
            };
        }

        export interface GetServiceAccountTokenProperties {
            apiToken?: outputs.workplace.v3.GetServiceAccountTokenPropertiesApiTokenProperties;
            success?: boolean;
        }
        /**
         * getServiceAccountTokenPropertiesProvideDefaults sets the appropriate defaults for GetServiceAccountTokenProperties
         */
        export function getServiceAccountTokenPropertiesProvideDefaults(val: GetServiceAccountTokenProperties): GetServiceAccountTokenProperties {
            return {
                ...val,
                success: (val.success) ?? true,
            };
        }

        export interface GetServiceAccountTokenPropertiesApiTokenProperties {
            createdAt?: string;
            expiresAt?: string;
            lastSeenAt?: string;
            name?: string;
            slug?: string;
        }

        export interface GetUserProperties {
            success?: boolean;
            workplaceUser?: outputs.workplace.v3.GetUserPropertiesWorkplaceUserProperties;
        }
        /**
         * getUserPropertiesProvideDefaults sets the appropriate defaults for GetUserProperties
         */
        export function getUserPropertiesProvideDefaults(val: GetUserProperties): GetUserProperties {
            return {
                ...val,
                success: (val.success) ?? true,
            };
        }

        export interface GetUserPropertiesWorkplaceUserProperties {
            access?: string;
            createdAt?: string;
            id?: string;
            user?: outputs.workplace.v3.GetUserPropertiesWorkplaceUserPropertiesUserProperties;
        }

        export interface GetUserPropertiesWorkplaceUserPropertiesUserProperties {
            email?: string;
            name?: string;
            profileImageUrl?: string;
            username?: string;
        }

        export interface GetWorkplaceProperties {
            workplace?: outputs.workplace.v3.GetWorkplacePropertiesWorkplaceProperties;
        }

        export interface GetWorkplacePropertiesWorkplaceProperties {
            billingEmail?: string;
            id?: string;
            name?: string;
            securityEmail?: string;
        }

        export interface GetWorkplaceRoleProperties {
            role?: outputs.workplace.v3.GetWorkplaceRolePropertiesRoleProperties;
        }
        /**
         * getWorkplaceRolePropertiesProvideDefaults sets the appropriate defaults for GetWorkplaceRoleProperties
         */
        export function getWorkplaceRolePropertiesProvideDefaults(val: GetWorkplaceRoleProperties): GetWorkplaceRoleProperties {
            return {
                ...val,
                role: (val.role ? outputs.workplace.v3.getWorkplaceRolePropertiesRolePropertiesProvideDefaults(val.role) : undefined),
            };
        }

        export interface GetWorkplaceRolePropertiesRoleProperties {
            createdAt?: string;
            identifier?: string;
            isCustomRole?: boolean;
            isInlineRole?: boolean;
            name?: string;
            permissions?: string[];
        }
        /**
         * getWorkplaceRolePropertiesRolePropertiesProvideDefaults sets the appropriate defaults for GetWorkplaceRolePropertiesRoleProperties
         */
        export function getWorkplaceRolePropertiesRolePropertiesProvideDefaults(val: GetWorkplaceRolePropertiesRoleProperties): GetWorkplaceRolePropertiesRoleProperties {
            return {
                ...val,
                isCustomRole: (val.isCustomRole) ?? true,
                isInlineRole: (val.isInlineRole) ?? true,
            };
        }

        export interface GroupProperties {
            createdAt?: string;
            defaultProjectRole?: outputs.workplace.v3.GroupPropertiesDefaultProjectRoleProperties;
            members?: outputs.workplace.v3.GroupPropertiesMembersItemProperties[];
            name?: string;
            projects?: outputs.workplace.v3.GroupPropertiesProjectsItemProperties[];
            slug?: string;
        }

        export interface GroupPropertiesDefaultProjectRoleProperties {
            identifier?: string;
        }

        export interface GroupPropertiesMembersItemProperties {
            slug?: string;
            type?: string;
        }

        export interface GroupPropertiesProjectsItemProperties {
            name?: string;
            role?: outputs.workplace.v3.GroupPropertiesProjectsItemPropertiesRoleProperties;
            slug?: string;
        }

        export interface GroupPropertiesProjectsItemPropertiesRoleProperties {
            identifier?: string;
        }

        export interface ListGroupsProperties {
            groups?: outputs.workplace.v3.ListGroupsPropertiesGroupsItemProperties[];
        }

        export interface ListGroupsPropertiesGroupsItemProperties {
            createdAt?: string;
            defaultProjectRole?: outputs.workplace.v3.ListGroupsPropertiesGroupsItemPropertiesDefaultProjectRoleProperties;
            name?: string;
            slug?: string;
        }

        export interface ListGroupsPropertiesGroupsItemPropertiesDefaultProjectRoleProperties {
            identifier?: string;
        }

        export interface ListInvitesProperties {
            invites?: outputs.workplace.v3.ListInvitesPropertiesInvitesItemProperties[];
        }

        export interface ListInvitesPropertiesInvitesItemProperties {
            createdAt?: string;
            email?: string;
            slug?: string;
            workplaceRole?: outputs.workplace.v3.ListInvitesPropertiesInvitesItemPropertiesWorkplaceRoleProperties;
        }
        /**
         * listInvitesPropertiesInvitesItemPropertiesProvideDefaults sets the appropriate defaults for ListInvitesPropertiesInvitesItemProperties
         */
        export function listInvitesPropertiesInvitesItemPropertiesProvideDefaults(val: ListInvitesPropertiesInvitesItemProperties): ListInvitesPropertiesInvitesItemProperties {
            return {
                ...val,
                workplaceRole: (val.workplaceRole ? outputs.workplace.v3.listInvitesPropertiesInvitesItemPropertiesWorkplaceRolePropertiesProvideDefaults(val.workplaceRole) : undefined),
            };
        }

        export interface ListInvitesPropertiesInvitesItemPropertiesWorkplaceRoleProperties {
            createdAt?: string;
            identifier?: string;
            isCustomRole?: boolean;
            isInlineRole?: boolean;
            name?: string;
            permissions?: string[];
        }
        /**
         * listInvitesPropertiesInvitesItemPropertiesWorkplaceRolePropertiesProvideDefaults sets the appropriate defaults for ListInvitesPropertiesInvitesItemPropertiesWorkplaceRoleProperties
         */
        export function listInvitesPropertiesInvitesItemPropertiesWorkplaceRolePropertiesProvideDefaults(val: ListInvitesPropertiesInvitesItemPropertiesWorkplaceRoleProperties): ListInvitesPropertiesInvitesItemPropertiesWorkplaceRoleProperties {
            return {
                ...val,
                isCustomRole: (val.isCustomRole) ?? true,
                isInlineRole: (val.isInlineRole) ?? true,
            };
        }

        export interface ListServiceAccountTokensProperties {
            apiTokens?: outputs.workplace.v3.ListServiceAccountTokensPropertiesApiTokensItemProperties[];
            success?: boolean;
        }
        /**
         * listServiceAccountTokensPropertiesProvideDefaults sets the appropriate defaults for ListServiceAccountTokensProperties
         */
        export function listServiceAccountTokensPropertiesProvideDefaults(val: ListServiceAccountTokensProperties): ListServiceAccountTokensProperties {
            return {
                ...val,
                success: (val.success) ?? true,
            };
        }

        export interface ListServiceAccountTokensPropertiesApiTokensItemProperties {
            createdAt?: string;
            expiresAt?: string;
            lastSeenAt?: string;
            name?: string;
            slug?: string;
        }

        export interface ListServiceAccountsProperties {
            serviceAccounts?: outputs.workplace.v3.ListServiceAccountsPropertiesServiceAccountsItemProperties[];
        }

        export interface ListServiceAccountsPropertiesServiceAccountsItemProperties {
            createdAt?: string;
            name?: string;
            slug?: string;
            workplaceRole?: outputs.workplace.v3.ListServiceAccountsPropertiesServiceAccountsItemPropertiesWorkplaceRoleProperties;
        }
        /**
         * listServiceAccountsPropertiesServiceAccountsItemPropertiesProvideDefaults sets the appropriate defaults for ListServiceAccountsPropertiesServiceAccountsItemProperties
         */
        export function listServiceAccountsPropertiesServiceAccountsItemPropertiesProvideDefaults(val: ListServiceAccountsPropertiesServiceAccountsItemProperties): ListServiceAccountsPropertiesServiceAccountsItemProperties {
            return {
                ...val,
                workplaceRole: (val.workplaceRole ? outputs.workplace.v3.listServiceAccountsPropertiesServiceAccountsItemPropertiesWorkplaceRolePropertiesProvideDefaults(val.workplaceRole) : undefined),
            };
        }

        export interface ListServiceAccountsPropertiesServiceAccountsItemPropertiesWorkplaceRoleProperties {
            createdAt?: string;
            identifier?: string;
            isCustomRole?: boolean;
            isInlineRole?: boolean;
            name?: string;
            permissions?: string[];
        }
        /**
         * listServiceAccountsPropertiesServiceAccountsItemPropertiesWorkplaceRolePropertiesProvideDefaults sets the appropriate defaults for ListServiceAccountsPropertiesServiceAccountsItemPropertiesWorkplaceRoleProperties
         */
        export function listServiceAccountsPropertiesServiceAccountsItemPropertiesWorkplaceRolePropertiesProvideDefaults(val: ListServiceAccountsPropertiesServiceAccountsItemPropertiesWorkplaceRoleProperties): ListServiceAccountsPropertiesServiceAccountsItemPropertiesWorkplaceRoleProperties {
            return {
                ...val,
                isCustomRole: (val.isCustomRole) ?? true,
                isInlineRole: (val.isInlineRole) ?? true,
            };
        }

        export interface ListUsersProperties {
            page?: number;
            success?: boolean;
            workplaceUsers?: outputs.workplace.v3.ListUsersPropertiesWorkplaceUsersItemProperties[];
        }
        /**
         * listUsersPropertiesProvideDefaults sets the appropriate defaults for ListUsersProperties
         */
        export function listUsersPropertiesProvideDefaults(val: ListUsersProperties): ListUsersProperties {
            return {
                ...val,
                page: (val.page) ?? 0,
                success: (val.success) ?? true,
            };
        }

        export interface ListUsersPropertiesWorkplaceUsersItemProperties {
            access?: string;
            createdAt?: string;
            id?: string;
            user?: outputs.workplace.v3.ListUsersPropertiesWorkplaceUsersItemPropertiesUserProperties;
        }

        export interface ListUsersPropertiesWorkplaceUsersItemPropertiesUserProperties {
            email?: string;
            name?: string;
            profileImageUrl?: string;
            username?: string;
        }

        export interface ListWorkplaceRolesPermissionsProperties {
            permissions?: string[];
        }

        export interface ListWorkplaceRolesProperties {
            roles?: outputs.workplace.v3.ListWorkplaceRolesPropertiesRolesItemProperties[];
        }

        export interface ListWorkplaceRolesPropertiesRolesItemProperties {
            createdAt?: string;
            identifier?: string;
            isCustomRole?: boolean;
            isInlineRole?: boolean;
            name?: string;
            permissions?: string[];
        }
        /**
         * listWorkplaceRolesPropertiesRolesItemPropertiesProvideDefaults sets the appropriate defaults for ListWorkplaceRolesPropertiesRolesItemProperties
         */
        export function listWorkplaceRolesPropertiesRolesItemPropertiesProvideDefaults(val: ListWorkplaceRolesPropertiesRolesItemProperties): ListWorkplaceRolesPropertiesRolesItemProperties {
            return {
                ...val,
                isCustomRole: (val.isCustomRole) ?? true,
                isInlineRole: (val.isInlineRole) ?? true,
            };
        }

        export interface RoleProperties {
            createdAt?: string;
            identifier?: string;
            isCustomRole?: boolean;
            isInlineRole?: boolean;
            name?: string;
            permissions?: string[];
        }
        /**
         * rolePropertiesProvideDefaults sets the appropriate defaults for RoleProperties
         */
        export function rolePropertiesProvideDefaults(val: RoleProperties): RoleProperties {
            return {
                ...val,
                isCustomRole: (val.isCustomRole) ?? true,
                isInlineRole: (val.isInlineRole) ?? true,
            };
        }

        export interface ServiceAccountProperties {
            createdAt?: string;
            name?: string;
            slug?: string;
            workplaceRole?: outputs.workplace.v3.ServiceAccountPropertiesWorkplaceRoleProperties;
        }
        /**
         * serviceAccountPropertiesProvideDefaults sets the appropriate defaults for ServiceAccountProperties
         */
        export function serviceAccountPropertiesProvideDefaults(val: ServiceAccountProperties): ServiceAccountProperties {
            return {
                ...val,
                workplaceRole: (val.workplaceRole ? outputs.workplace.v3.serviceAccountPropertiesWorkplaceRolePropertiesProvideDefaults(val.workplaceRole) : undefined),
            };
        }

        export interface ServiceAccountPropertiesWorkplaceRoleProperties {
            createdAt?: string;
            identifier?: string;
            isCustomRole?: boolean;
            isInlineRole?: boolean;
            name?: string;
            permissions?: string[];
        }
        /**
         * serviceAccountPropertiesWorkplaceRolePropertiesProvideDefaults sets the appropriate defaults for ServiceAccountPropertiesWorkplaceRoleProperties
         */
        export function serviceAccountPropertiesWorkplaceRolePropertiesProvideDefaults(val: ServiceAccountPropertiesWorkplaceRoleProperties): ServiceAccountPropertiesWorkplaceRoleProperties {
            return {
                ...val,
                isCustomRole: (val.isCustomRole) ?? true,
                isInlineRole: (val.isInlineRole) ?? true,
            };
        }

        export interface WorkplaceProperties {
            billingEmail?: string;
            id?: string;
            name?: string;
            securityEmail?: string;
        }

        /**
         * You may provide an identifier OR permissions, but not both
         */
        export interface WorkplaceRoleProperties {
            /**
             * Identifier of an existing workplace role
             */
            identifier?: string;
            /**
             * Workplace permissions to grant
             */
            permissions?: string[];
        }

    }
}
