// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DopplerNative.ConfigsV3
{
    [DopplerNativeResourceType("doppler-native:configs/v3:Configs")]
    public partial class Configs : global::Pulumi.CustomResource
    {
        [Output("config")]
        public Output<Outputs.ConfigProperties?> Config { get; private set; } = null!;

        /// <summary>
        /// Identifier for the environment object.
        /// </summary>
        [Output("environment")]
        public Output<string> Environment { get; private set; } = null!;

        /// <summary>
        /// Name of the new branch config.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Unique identifier for the project object.
        /// </summary>
        [Output("project")]
        public Output<string> Project { get; private set; } = null!;


        /// <summary>
        /// Create a Configs resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Configs(string name, ConfigsArgs args, CustomResourceOptions? options = null)
            : base("doppler-native:configs/v3:Configs", name, args ?? new ConfigsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Configs(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("doppler-native:configs/v3:Configs", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-doppler-native",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Configs resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Configs Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Configs(name, id, options);
        }
    }

    public sealed class ConfigsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Identifier for the environment object.
        /// </summary>
        [Input("environment", required: true)]
        public Input<string> Environment { get; set; } = null!;

        /// <summary>
        /// Name of the new branch config.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Unique identifier for the project object.
        /// </summary>
        [Input("project", required: true)]
        public Input<string> Project { get; set; } = null!;

        public ConfigsArgs()
        {
            Environment = "ENVIRONMENT_ID";
            Name = "CONFIG_NAME";
            Project = "PROJECT_NAME";
        }
        public static new ConfigsArgs Empty => new ConfigsArgs();
    }
}
