// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DopplerNative.ConfigsV3
{
    public static class GetConfigLog
    {
        public static Task<GetConfigLogResult> InvokeAsync(GetConfigLogArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetConfigLogResult>("doppler-native:configs/v3:getConfigLog", args ?? new GetConfigLogArgs(), options.WithDefaults());

        public static Output<GetConfigLogResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetConfigLogResult>("doppler-native:configs/v3:getConfigLog", InvokeArgs.Empty, options.WithDefaults());
    }


    public sealed class GetConfigLogArgs : global::Pulumi.InvokeArgs
    {
        public GetConfigLogArgs()
        {
        }
        public static new GetConfigLogArgs Empty => new GetConfigLogArgs();
    }


    [OutputType]
    public sealed class GetConfigLogResult
    {
        public readonly Outputs.GetConfigLogProperties Items;

        [OutputConstructor]
        private GetConfigLogResult(Outputs.GetConfigLogProperties items)
        {
            Items = items;
        }
    }
}
