// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DopplerNative.WorkplaceV3.Outputs
{

    [OutputType]
    public sealed class GetServiceAccountTokenPropertiesApiTokenProperties
    {
        public readonly string? CreatedAt;
        public readonly string? ExpiresAt;
        public readonly string? LastSeenAt;
        public readonly string? Name;
        public readonly string? Slug;

        [OutputConstructor]
        private GetServiceAccountTokenPropertiesApiTokenProperties(
            string? createdAt,

            string? expiresAt,

            string? lastSeenAt,

            string? name,

            string? slug)
        {
            CreatedAt = createdAt;
            ExpiresAt = expiresAt;
            LastSeenAt = lastSeenAt;
            Name = name;
            Slug = slug;
        }
    }
}
