// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DopplerNative.WorkplaceV3.Outputs
{

    [OutputType]
    public sealed class GetUserPropertiesWorkplaceUserPropertiesUserProperties
    {
        public readonly string? Email;
        public readonly string? Name;
        public readonly string? ProfileImageUrl;
        public readonly string? Username;

        [OutputConstructor]
        private GetUserPropertiesWorkplaceUserPropertiesUserProperties(
            string? email,

            string? name,

            string? profileImageUrl,

            string? username)
        {
            Email = email;
            Name = name;
            ProfileImageUrl = profileImageUrl;
            Username = username;
        }
    }
}
