// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DopplerNative.WorkplaceV3.Outputs
{

    [OutputType]
    public sealed class ListUsersPropertiesWorkplaceUsersItemProperties
    {
        public readonly string? Access;
        public readonly string? CreatedAt;
        public readonly string? Id;
        public readonly Outputs.ListUsersPropertiesWorkplaceUsersItemPropertiesUserProperties? User;

        [OutputConstructor]
        private ListUsersPropertiesWorkplaceUsersItemProperties(
            string? access,

            string? createdAt,

            string? id,

            Outputs.ListUsersPropertiesWorkplaceUsersItemPropertiesUserProperties? user)
        {
            Access = access;
            CreatedAt = createdAt;
            Id = id;
            User = user;
        }
    }
}
