// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DopplerNative.WorkplaceV3.Outputs
{

    [OutputType]
    public sealed class ListUsersProperties
    {
        public readonly int? Page;
        public readonly bool? Success;
        public readonly ImmutableArray<Outputs.ListUsersPropertiesWorkplaceUsersItemProperties> WorkplaceUsers;

        [OutputConstructor]
        private ListUsersProperties(
            int? page,

            bool? success,

            ImmutableArray<Outputs.ListUsersPropertiesWorkplaceUsersItemProperties> workplaceUsers)
        {
            Page = page;
            Success = success;
            WorkplaceUsers = workplaceUsers;
        }
    }
}
