// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v3

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-doppler-native/sdk/go/doppler-native/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func ListServiceAccounts(ctx *pulumi.Context, args *ListServiceAccountsArgs, opts ...pulumi.InvokeOption) (*ListServiceAccountsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ListServiceAccountsResult
	err := ctx.Invoke("doppler-native:workplace/v3:listServiceAccounts", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ListServiceAccountsArgs struct {
}

type ListServiceAccountsResult struct {
	Items ListServiceAccountsProperties `pulumi:"items"`
}

func ListServiceAccountsOutput(ctx *pulumi.Context, args ListServiceAccountsOutputArgs, opts ...pulumi.InvokeOption) ListServiceAccountsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ListServiceAccountsResult, error) {
			args := v.(ListServiceAccountsArgs)
			r, err := ListServiceAccounts(ctx, &args, opts...)
			var s ListServiceAccountsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(ListServiceAccountsResultOutput)
}

type ListServiceAccountsOutputArgs struct {
}

func (ListServiceAccountsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ListServiceAccountsArgs)(nil)).Elem()
}

type ListServiceAccountsResultOutput struct{ *pulumi.OutputState }

func (ListServiceAccountsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListServiceAccountsResult)(nil)).Elem()
}

func (o ListServiceAccountsResultOutput) ToListServiceAccountsResultOutput() ListServiceAccountsResultOutput {
	return o
}

func (o ListServiceAccountsResultOutput) ToListServiceAccountsResultOutputWithContext(ctx context.Context) ListServiceAccountsResultOutput {
	return o
}

func (o ListServiceAccountsResultOutput) Items() ListServiceAccountsPropertiesOutput {
	return o.ApplyT(func(v ListServiceAccountsResult) ListServiceAccountsProperties { return v.Items }).(ListServiceAccountsPropertiesOutput)
}

func init() {
	pulumi.RegisterOutputType(ListServiceAccountsResultOutput{})
}
