// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.DopplerNative.WorkplaceV3.Outputs
{

    [OutputType]
    public sealed class GetServiceAccountTokenProperties
    {
        public readonly Outputs.GetServiceAccountTokenPropertiesApiTokenProperties? ApiToken;
        public readonly bool? Success;

        [OutputConstructor]
        private GetServiceAccountTokenProperties(
            Outputs.GetServiceAccountTokenPropertiesApiTokenProperties? apiToken,

            bool? success)
        {
            ApiToken = apiToken;
            Success = success;
        }
    }
}
