// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.DopplerNative.WorkplaceV3.Outputs
{

    /// <summary>
    /// You may provide an identifier OR permissions, but not both
    /// </summary>
    [OutputType]
    public sealed class WorkplaceRoleProperties
    {
        /// <summary>
        /// Identifier of an existing workplace role
        /// </summary>
        public readonly string? Identifier;
        /// <summary>
        /// Workplace permissions to grant
        /// </summary>
        public readonly ImmutableArray<string> Permissions;

        [OutputConstructor]
        private WorkplaceRoleProperties(
            string? identifier,

            ImmutableArray<string> permissions)
        {
            Identifier = identifier;
            Permissions = permissions;
        }
    }
}
