# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from ... import _utilities
from . import outputs

__all__ = [
    'GetProjectMemberResult',
    'AwaitableGetProjectMemberResult',
    'get_project_member',
    'get_project_member_output',
]

@pulumi.output_type
class GetProjectMemberResult:
    def __init__(__self__, items=None):
        if items and not isinstance(items, dict):
            raise TypeError("Expected argument 'items' to be a dict")
        pulumi.set(__self__, "items", items)

    @property
    @pulumi.getter
    def items(self) -> 'outputs.GetProjectMemberProperties':
        return pulumi.get(self, "items")


class AwaitableGetProjectMemberResult(GetProjectMemberResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetProjectMemberResult(
            items=self.items)


def get_project_member(slug: Optional[str] = None,
                       type: Optional[str] = None,
                       opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetProjectMemberResult:
    """
    Use this data source to access information about an existing resource.

    :param str slug: Member's slug
    """
    __args__ = dict()
    __args__['slug'] = slug
    __args__['type'] = type
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('doppler-native:projects/v3:getProjectMember', __args__, opts=opts, typ=GetProjectMemberResult).value

    return AwaitableGetProjectMemberResult(
        items=pulumi.get(__ret__, 'items'))


@_utilities.lift_output_func(get_project_member)
def get_project_member_output(slug: Optional[pulumi.Input[str]] = None,
                              type: Optional[pulumi.Input[str]] = None,
                              opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetProjectMemberResult]:
    """
    Use this data source to access information about an existing resource.

    :param str slug: Member's slug
    """
    ...
