# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from ... import _utilities
from . import outputs

__all__ = [
    'ListProjectRolesPermissionsResult',
    'AwaitableListProjectRolesPermissionsResult',
    'list_project_roles_permissions',
    'list_project_roles_permissions_output',
]

@pulumi.output_type
class ListProjectRolesPermissionsResult:
    def __init__(__self__, items=None):
        if items and not isinstance(items, dict):
            raise TypeError("Expected argument 'items' to be a dict")
        pulumi.set(__self__, "items", items)

    @property
    @pulumi.getter
    def items(self) -> 'outputs.ListProjectRolesPermissionsProperties':
        return pulumi.get(self, "items")


class AwaitableListProjectRolesPermissionsResult(ListProjectRolesPermissionsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ListProjectRolesPermissionsResult(
            items=self.items)


def list_project_roles_permissions(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableListProjectRolesPermissionsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('doppler-native:projects/v3:listProjectRolesPermissions', __args__, opts=opts, typ=ListProjectRolesPermissionsResult).value

    return AwaitableListProjectRolesPermissionsResult(
        items=pulumi.get(__ret__, 'items'))


@_utilities.lift_output_func(list_project_roles_permissions)
def list_project_roles_permissions_output(opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[ListProjectRolesPermissionsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
