// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export function getSync(args?: GetSyncArgs, opts?: pulumi.InvokeOptions): Promise<GetSyncResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("doppler-native:configs/v3:getSync", {
    }, opts);
}

export interface GetSyncArgs {
}

export interface GetSyncResult {
    readonly items: outputs.configs.v3.GetSyncProperties;
}
export function getSyncOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetSyncResult> {
    return pulumi.output(getSync(opts))
}
