// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export class SecretsUpdate extends pulumi.CustomResource {
    /**
     * Get an existing SecretsUpdate resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): SecretsUpdate {
        return new SecretsUpdate(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler-native:configs/v3:SecretsUpdate';

    /**
     * Returns true if the given object is an instance of SecretsUpdate.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecretsUpdate {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecretsUpdate.__pulumiType;
    }

    /**
     * Either `secrets` or `change_requests` is required (can't use both). Object of secrets you would like to save to the config. Try it with the sample secrets below.
     */
    public readonly changeRequests!: pulumi.Output<outputs.configs.v3.ChangeRequestsItemProperties[] | undefined>;
    /**
     * Name of the config object.
     */
    public readonly config!: pulumi.Output<string>;
    /**
     * Unique identifier for the project object.
     */
    public readonly project!: pulumi.Output<string>;
    public readonly secrets!: pulumi.Output<outputs.configs.v3.SecretsProperties | undefined>;

    /**
     * Create a SecretsUpdate resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecretsUpdateArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.config === undefined) && !opts.urn) {
                throw new Error("Missing required property 'config'");
            }
            if ((!args || args.project === undefined) && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            resourceInputs["changeRequests"] = args ? args.changeRequests : undefined;
            resourceInputs["config"] = (args ? args.config : undefined) ?? "CONFIG_NAME";
            resourceInputs["project"] = (args ? args.project : undefined) ?? "PROJECT_NAME";
            resourceInputs["secrets"] = args ? args.secrets : undefined;
        } else {
            resourceInputs["changeRequests"] = undefined /*out*/;
            resourceInputs["config"] = undefined /*out*/;
            resourceInputs["project"] = undefined /*out*/;
            resourceInputs["secrets"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SecretsUpdate.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a SecretsUpdate resource.
 */
export interface SecretsUpdateArgs {
    /**
     * Either `secrets` or `change_requests` is required (can't use both). Object of secrets you would like to save to the config. Try it with the sample secrets below.
     */
    changeRequests?: pulumi.Input<pulumi.Input<inputs.configs.v3.ChangeRequestsItemPropertiesArgs>[]>;
    /**
     * Name of the config object.
     */
    config: pulumi.Input<string>;
    /**
     * Unique identifier for the project object.
     */
    project: pulumi.Input<string>;
    /**
     * Either `secrets` or `change_requests` is required (can't use both). Object of secrets you would like to save to the config. Try it with the sample secrets below.
     */
    secrets?: pulumi.Input<inputs.configs.v3.SecretsPropertiesArgs>;
}
