// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v3

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-doppler-native/sdk/go/doppler-native/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetAuthMe(ctx *pulumi.Context, args *GetAuthMeArgs, opts ...pulumi.InvokeOption) (*GetAuthMeResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAuthMeResult
	err := ctx.Invoke("doppler-native:me/v3:getAuthMe", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetAuthMeArgs struct {
}

type GetAuthMeResult struct {
	Items GetAuthMeProperties `pulumi:"items"`
}

func GetAuthMeOutput(ctx *pulumi.Context, args GetAuthMeOutputArgs, opts ...pulumi.InvokeOption) GetAuthMeResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetAuthMeResult, error) {
			args := v.(GetAuthMeArgs)
			r, err := GetAuthMe(ctx, &args, opts...)
			var s GetAuthMeResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetAuthMeResultOutput)
}

type GetAuthMeOutputArgs struct {
}

func (GetAuthMeOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAuthMeArgs)(nil)).Elem()
}

type GetAuthMeResultOutput struct{ *pulumi.OutputState }

func (GetAuthMeResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAuthMeResult)(nil)).Elem()
}

func (o GetAuthMeResultOutput) ToGetAuthMeResultOutput() GetAuthMeResultOutput {
	return o
}

func (o GetAuthMeResultOutput) ToGetAuthMeResultOutputWithContext(ctx context.Context) GetAuthMeResultOutput {
	return o
}

func (o GetAuthMeResultOutput) Items() GetAuthMePropertiesOutput {
	return o.ApplyT(func(v GetAuthMeResult) GetAuthMeProperties { return v.Items }).(GetAuthMePropertiesOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAuthMeResultOutput{})
}
