// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.DopplerNative.EnvironmentsV3.Outputs
{

    [OutputType]
    public sealed class EnvironmentProperties
    {
        public readonly string? CreatedAt;
        public readonly string? Id;
        public readonly string? InitialFetchAt;
        public readonly string? Name;
        public readonly string? Project;

        [OutputConstructor]
        private EnvironmentProperties(
            string? createdAt,

            string? id,

            string? initialFetchAt,

            string? name,

            string? project)
        {
            CreatedAt = createdAt;
            Id = id;
            InitialFetchAt = initialFetchAt;
            Name = name;
            Project = project;
        }
    }
}
